# Generated by Django 5.2.8 on 2025-12-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0002_calculation_custpagelocation_equipmentcost_jobcost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedequip',
            name='conid',
        ),
        migrations.RemoveField(
            model_name='selectedequip',
            name='custid',
        ),
    ]
