# Generated by Django 5.2.8 on 2025-12-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0003_remove_selectedequip_conid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedequip',
            name='conid',
            field=models.IntegerField(default=None, null=True, verbose_name='ConID.'),
        ),
        migrations.AddField(
            model_name='selectedequip',
            name='custid',
            field=models.IntegerField(default=None, null=True, verbose_name='CustID.'),
        ),
    ]
