# Generated by Django 5.2.8 on 2025-12-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0004_selectedequip_conid_selectedequip_custid'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaljobcost',
            name='conid',
            field=models.IntegerField(default=None, null=True, verbose_name='ConID.'),
        ),
        migrations.AddField(
            model_name='totaljobcost',
            name='custid',
            field=models.IntegerField(default=None, null=True, verbose_name='CustID.'),
        ),
    ]
