# Generated by Django 5.2.8 on 2025-12-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0005_totaljobcost_conid_totaljobcost_custid'),
    ]

    operations = [
        migrations.AddField(
            model_name='custpagelocation',
            name='conid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
