# Generated by Django 5.2.8 on 2026-01-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0006_custpagelocation_conid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
