# Generated by Django 5.2.8 on 2026-01-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0007_alter_profit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.'),
        ),
    ]
