# Generated by Django 5.2.8 on 2026-01-02 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0008_alter_profit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcost',
            name='netprofit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mhadatabase.profit', verbose_name=''),
        ),
    ]
