# Generated by Django 5.2.8 on 2026-01-02 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0009_alter_jobcost_netprofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcost',
            name='netprofit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mhadatabase.profit', to_field='netprofit', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profit',
            name='netprofit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, unique=True, verbose_name=''),
        ),
    ]
