# Generated by Django 5.2.8 on 2026-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0010_alter_jobcost_netprofit_alter_profit_netprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='custpagelocation',
            name='bidid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
