# Generated by Django 5.2.8 on 2026-01-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0011_custpagelocation_bidid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaljobcost',
            name='descripid',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name=''),
        ),
    ]
