# Generated by Django 5.2.8 on 2026-01-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0012_alter_totaljobcost_descripid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetProfit',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('conid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('custid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('jobid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('bidid', models.IntegerField(default=None, null=True, verbose_name='')),
                ('targetprofit', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='')),
            ],
        ),
    ]
