# Generated by Django 5.2.8 on 2026-01-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0016_alter_targetprofit_targetprofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetprofit',
            name='targetprofit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
    ]
