# Generated by Django 5.2.8 on 2026-01-05 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0017_alter_targetprofit_targetprofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetprofit',
            name='targetprofit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mhadatabase.profit', to_field='netprofit', verbose_name=''),
        ),
    ]
