# Generated by Django 5.2.8 on 2026-01-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0018_alter_targetprofit_targetprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedequip',
            name='jobid',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
