# Generated by Django 5.2.8 on 2026-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0019_selectedequip_jobid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptiontherm',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('thermdescriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mfgmodeldescriptherm',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('thermmfgmodeldescrip', models.CharField(max_length=45, verbose_name='')),
            ],
        ),
    ]
