# Generated by Django 5.2.8 on 2026-02-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0020_descriptiontherm_mfgmodeldescriptherm'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment2',
            name='config3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='config3'),
        ),
    ]
