# Generated by Django 5.2.8 on 2026-02-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0021_equipment2_config3'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment2',
            name='config4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='config4'),
        ),
    ]
