# Generated by Django 5.2.8 on 2026-02-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0022_equipment2_config4'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTherm',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('therms', models.CharField(max_length=45, verbose_name='')),
            ],
        ),
    ]
