# Generated by Django 5.2.8 on 2026-02-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0023_configtherm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTUtherm',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('thermbtus', models.CharField(max_length=45, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Gasvivtherm',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('thermgasvivs', models.CharField(max_length=45, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Motortypetherm',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('thermmotortypes', models.CharField(max_length=45, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Outputstg1therm',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('thermoutputstg1s', models.CharField(max_length=45, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Refrigetherm',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('thermrefrigs', models.CharField(max_length=45, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Thermeff',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('efftherm', models.CharField(max_length=45, verbose_name='')),
            ],
        ),
    ]
