# Generated by Django 5.2.8 on 2026-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0024_btutherm_gasvivtherm_motortypetherm_outputstg1therm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outputstg2furn',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('outputstg2furns', models.CharField(max_length=45, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Outputstg3furn',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('outputstg3furns', models.CharField(max_length=45, verbose_name='')),
            ],
        ),
    ]
