# Generated by Django 5.2.8 on 2026-02-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0025_outputstg2furn_outputstg3furn'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment2',
            name='eff3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='eff2'),
        ),
        migrations.AddField(
            model_name='equipment2',
            name='eff4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='eff2'),
        ),
    ]
