# Generated by Django 5.2.8 on 2026-02-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0026_equipment2_eff3_equipment2_eff4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment2',
            name='eff3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='eff3'),
        ),
        migrations.AlterField(
            model_name='equipment2',
            name='eff4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='eff3'),
        ),
    ]
