# Generated by Django 5.2.8 on 2026-02-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0027_alter_equipment2_eff3_alter_equipment2_eff4'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment2',
            name='btu3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='btu3'),
        ),
        migrations.AddField(
            model_name='equipment2',
            name='btu4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='btu4'),
        ),
        migrations.AddField(
            model_name='equipment2',
            name='description3',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='description3'),
        ),
        migrations.AddField(
            model_name='equipment2',
            name='description4',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='description4'),
        ),
        migrations.AddField(
            model_name='equipment2',
            name='description5',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='description5'),
        ),
        migrations.AddField(
            model_name='equipment2',
            name='mfgmodeldescrip3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mfgmodeldescrip3'),
        ),
        migrations.AddField(
            model_name='equipment2',
            name='mfgmodeldescrip4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mfgmodeldescrip4'),
        ),
        migrations.AddField(
            model_name='equipment2',
            name='mfgmodeldescrip5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mfgmodeldescrip5'),
        ),
        migrations.AddField(
            model_name='equipment2',
            name='refrig3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='refrig3'),
        ),
        migrations.AddField(
            model_name='equipment2',
            name='refrig4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='refrig4'),
        ),
    ]
