# Generated by Django 5.2.8 on 2026-02-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0028_equipment2_btu3_equipment2_btu4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtermodelnum',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('modelnumfilter', models.CharField(max_length=45, verbose_name='')),
            ],
        ),
    ]
