# Generated by Django 5.2.8 on 2026-03-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0029_filtermodelnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartThermostat',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('smart', models.CharField(max_length=45, unique=True, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='equipment2',
            name='smart',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='smart:'),
        ),
    ]
