# Generated by Django 5.2.8 on 2026-03-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0030_smartthermostat_alter_equipment2_smart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment2',
            name='smart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mhadatabase.smartthermostat', verbose_name='Smart Thermostat:'),
        ),
    ]
