# Generated by Django 5.2.8 on 2026-03-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0031_alter_equipment2_smart'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercoilall',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='equipselection',
            name='joblocation',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='filterfurnconfig',
            name='furnconfigfilter',
            field=models.CharField(blank=True, default=None, max_length=75, verbose_name=''),
        ),

    ]
