# Generated by Django 5.2.8 on 2026-03-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0032_filtercoilall_type_alter_equipselection_joblocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblocation',
            name='jobloc',
            field=models.CharField(blank=True, default=None, max_length=75, null=True, unique=True, verbose_name=''),
        ),
    ]
