# Generated by Django 5.2.8 on 2026-03-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0033_alter_joblocation_jobloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterfurnconfig',
            name='furnconfigfilter',
            field=models.CharField(blank=True, default=None, max_length=75, unique=True, verbose_name=''),
        ),
    ]
