# Generated by Django 5.2.8 on 2026-03-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0034_alter_filterfurnconfig_furnconfigfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercoilall',
            name='type',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
    ]
