# Generated by Django 5.2.8 on 2026-03-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0035_alter_filtercoilall_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPlenumWidth',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('furnplenumwidth', models.CharField(blank=True, default=None, max_length=75, null=True, verbose_name='')),
            ],
        ),
    ]
