# Generated by Django 5.2.8 on 2026-03-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0036_filterplenumwidth'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnaceWidth',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('furnwidth', models.CharField(blank=True, default=None, max_length=75, null=True, verbose_name='')),
            ],
        ),
    ]
