# Generated by Django 5.2.8 on 2026-03-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0037_furnacewidth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FurnaceWidth',
        ),
    ]
