# Generated by Django 5.2.8 on 2026-03-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0038_delete_furnacewidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterplenumwidth',
            name='furnplenumwidth',
            field=models.CharField(blank=True, default=None, max_length=75, null=True, unique=True, verbose_name=''),
        ),
    ]
