# Generated by Django 5.2.8 on 2026-03-23 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0039_alter_filterplenumwidth_furnplenumwidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipselection',
            name='plenumwidth',
            field=models.ForeignKey(blank=True, default='0.00', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plenumwidth', to='mhadatabase.filterplenumwidth', to_field='furnplenumwidth', verbose_name=''),
        ),
    ]
