# Generated by Django 5.2.8 on 2026-03-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0040_alter_equipselection_plenumwidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipselection',
            name='plenumwidth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
    ]
