# Generated by Django 5.2.8 on 2026-03-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0041_alter_equipselection_plenumwidth'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipselection',
            name='existfurnconfig',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='equipselection',
            name='existfurndepth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='equipselection',
            name='existfurnheight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
        migrations.AddField(
            model_name='equipselection',
            name='existfurnwidth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
    ]
