# Generated by Django 5.2.8 on 2026-03-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0042_equipselection_existfurnconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistFurnConfig',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('furnconfig', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
            ],
        ),
    ]
