# Generated by Django 5.2.8 on 2026-04-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0043_existfurnconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipselection',
            name='existfurnconfig',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
    ]
