# Generated by Django 5.2.8 on 2026-04-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0044_alter_equipselection_existfurnconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipselection',
            name='coildescript',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
    ]
