# Generated by Django 5.2.8 on 2026-04-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0045_equipselection_coildescript'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercoilmodelnum',
            name='coildepth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
    ]
