# Generated by Django 5.2.8 on 2026-04-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0046_filtercoilmodelnum_coildepth'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipselection',
            name='addthermostat',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name=''),
        ),
    ]
