# Generated by Django 5.2.8 on 2026-04-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0047_equipselection_addthermostat'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNo',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('noyes', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
            ],
        ),
    ]
