# Generated by Django 5.2.8 on 2026-05-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0048_yesno'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
