# Generated by Django 5.2.8 on 2026-05-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0049_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='memo10a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo11a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo12a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo13a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo14a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo15a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo16a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo17a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo18a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo19a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo1a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo20a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo21a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo22a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo23a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo24a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo25a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo26a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo27a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo28a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo29a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo2a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo30a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo31a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo3a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo4a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo5a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo6a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo7a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo8a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo9a',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name=''),
        ),
    ]
