# Generated by Django 5.2.8 on 2026-05-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0050_contract_memo10a_contract_memo11a_contract_memo12a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='memo31',
            field=models.TextField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
