# Generated by Django 5.2.8 on 2026-05-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0052_contract_deposit_currency_alter_contract_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='deposit_currency',
        ),
        migrations.AlterField(
            model_name='contract',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name=''),
        ),
    ]
