# Generated by Django 5.2.8 on 2026-05-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0055_remove_contract_deposit_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='deposittermsa',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='finaltermsa',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name=''),
        ),
    ]
