# Generated by Django 5.2.8 on 2026-05-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0056_contract_deposittermsa_contract_finaltermsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='descript4b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='jobtype4b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
    ]
