# Generated by Django 5.2.8 on 2026-05-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0057_bidding_descript4b_bidding_jobtype4b'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='descript1b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript2b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript3b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='jobtype1b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='jobtype2b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='jobtype3b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
    ]
