# Generated by Django 5.2.8 on 2026-05-14 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0058_bidding_descript1b_bidding_descript2b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='quanity8',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quanity8', to='mhadatabase.quanity', verbose_name=''),
        ),
    ]
