# Generated by Django 5.2.8 on 2026-05-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0059_alter_bidding_quanity8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='quanity8',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
