# Generated by Django 5.2.8 on 2026-05-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0061_remove_bidding_descript10b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatType',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('type', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
            ],
        ),
    ]
