# Generated by Django 5.2.8 on 2026-05-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0063_material1_material2'),
    ]

    operations = [
        migrations.CreateModel(
            name='material3',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('type', models.CharField(blank=True, default=None, max_length=75, null=True, verbose_name='')),
            ],
        ),
    ]
