# Generated by Django 5.2.8 on 2026-05-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0064_material3'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='descript8b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
    ]
