# Generated by Django 5.2.8 on 2026-05-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0065_bidding_descript8b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descrip',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name=''),
        ),
    ]
