# Generated by Django 5.2.8 on 2026-05-19 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0066_alter_material_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript8',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript8', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
    ]
