# Generated by Django 5.2.8 on 2026-05-19 20:39

import django.db.models.deletion
import mhadatabase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0067_alter_bidding_descript8'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='descript10b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript11b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript12b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript13b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript14b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript15b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript16b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript17b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript18b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript9b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript8',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=mhadatabase.models.limit_descript8b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript8', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
    ]
