# Generated by Django 5.2.8 on 2026-05-19 20:50

import django.db.models.deletion
import mhadatabase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0068_bidding_descript10b_bidding_descript11b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript9b',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=mhadatabase.models.limit_descript9b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript9', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
    ]
