# Generated by Django 5.2.8 on 2026-05-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0072_alter_bidding_descript10b_alter_bidding_descript11b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='mattype',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
