# Generated by Django 5.2.8 on 2026-05-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0073_alter_bidding_mattype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript8b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
    ]
