# Generated by Django 5.2.8 on 2026-05-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0074_alter_bidding_descript8b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript10b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript11b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript12b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript13b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript14b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript15b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript16b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript17b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript18b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript9b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
    ]
