# Generated by Django 5.2.8 on 2026-05-22 19:55

import django.db.models.deletion
import mhadatabase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0076_alter_bidding_descript8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript8',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=mhadatabase.models.limit_descript8b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript8', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
    ]
