# Generated by Django 5.2.8 on 2026-05-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0079_alter_bidding_descript8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mattypebid',
            name='type',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name=''),
        ),
    ]
