# Generated by Django 5.2.8 on 2026-05-24 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0080_alter_mattypebid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript8',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript8', to='mhadatabase.mattypebid', to_field='type', verbose_name=''),
        ),
    ]
