# Generated by Django 5.2.8 on 2026-05-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0081_alter_bidding_descript8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript8',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
    ]
