# Generated by Django 5.2.8 on 2026-05-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0083_alter_bidding_descript8'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='packageid',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
