# Generated by Django 5.2.8 on 2026-05-24 14:33

import django.db.models.deletion
import mhadatabase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0085_alter_bidding_descript8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript10',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript10b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript10', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript11',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript11b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript11', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript12',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript12b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript12', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript13',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript13b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript13', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript14',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript14b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript14', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript15',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript15b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript15', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript16',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript16b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript16', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript17',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript17b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript17', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript18',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript18b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript18', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript9',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript9b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript9', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
    ]
