# Generated by Django 5.2.8 on 2026-05-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0086_alter_bidding_descript10_alter_bidding_descript11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterequiptype',
            name='typeequip',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name=''),
        ),
    ]
