# Generated by Django 5.2.8 on 2026-05-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0087_alter_filterequiptype_typeequip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='jobtype1',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype1b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
    ]
