# Generated by Django 5.2.8 on 2026-05-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0088_alter_bidding_jobtype1_alter_bidding_jobtype1b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='types',
            field=models.CharField(max_length=45, unique=True, verbose_name=''),
        ),
    ]
