# Generated by Django 5.2.8 on 2026-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0089_alter_type_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='jobtype1',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
