# Generated by Django 5.2.8 on 2026-05-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0090_alter_bidding_jobtype1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment2',
            name='modelnum',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Model #:'),
        ),
    ]
