# Generated by Django 5.2.8 on 2026-05-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0091_alter_equipment2_modelnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript1b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
    ]
