# Generated by Django 5.2.8 on 2026-05-25 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0092_alter_bidding_descript1b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript1',
            field=models.ForeignKey(blank=True, default='Select Equipment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript8', to='mhadatabase.equipment2', to_field='modelnum', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript1b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
    ]
