# Generated by Django 5.2.8 on 2026-05-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0094_alter_bidding_descript1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript1',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
    ]
