# Generated by Django 5.2.8 on 2026-05-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0095_alter_bidding_descript1'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterequiptype',
            name='typeid',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
