# Generated by Django 5.2.8 on 2026-05-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0096_filterequiptype_typeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment2',
            name='equipid',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
