# Generated by Django 5.2.8 on 2026-05-25 14:31

import django.db.models.deletion
import mhadatabase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0097_equipment2_equipid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript1',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript1b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript1', to='mhadatabase.equipment2', to_field='modelnum', verbose_name=''),
        ),
    ]
