# Generated by Django 5.2.8 on 2026-05-25 19:51

import django.db.models.deletion
import mhadatabase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0099_alter_bidding_descript2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript3',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript3b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript3', to='mhadatabase.equipment2', to_field='modelnum', verbose_name=''),
        ),
    ]
