# Generated by Django 5.2.8 on 2026-05-25 19:53

import django.db.models.deletion
import mhadatabase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0100_alter_bidding_descript3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript4',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript4b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript4', to='mhadatabase.equipment2', to_field='modelnum', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript5',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript5b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript5', to='mhadatabase.equipment2', to_field='modelnum', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript6',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript6b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript6', to='mhadatabase.equipment2', to_field='modelnum', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript7',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript7b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript7', to='mhadatabase.equipment2', to_field='modelnum', verbose_name=''),
        ),
    ]
