# Generated by Django 5.2.8 on 2026-05-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0103_alter_bidding_descript8'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterTypeDescrip2',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('mfg', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('modnum', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('mfgdescrip', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='FilterTypeDescrip3',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('mfg', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('modnum', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('mfgdescrip', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='FilterTypeDescrip4',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('mfg', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('modnum', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('mfgdescrip', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='FilterTypeDescrip5',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('mfg', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('modnum', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('mfgdescrip', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='FilterTypeDescrip6',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('mfg', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('modnum', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('mfgdescrip', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='FilterTypeDescrip7',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID.')),
                ('mfg', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('modnum', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
                ('mfgdescrip', models.CharField(blank=True, max_length=45, null=True, verbose_name='')),
            ],
        ),
    ]
