# Generated by Django 5.2.8 on 2026-05-25 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0106_alter_bidding_descript1_alter_bidding_descript2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript2',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=6, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript2', to='mhadatabase.equipment2', to_field='modelnum', verbose_name='Descript2'),
        ),
    ]
