# Generated by Django 5.2.8 on 2026-05-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0108_alter_bidding_descript2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterTypeDescrip',
        ),
        migrations.DeleteModel(
            name='FilterTypeDescrip2',
        ),
        migrations.DeleteModel(
            name='FilterTypeDescrip3',
        ),
        migrations.DeleteModel(
            name='FilterTypeDescrip4',
        ),
        migrations.DeleteModel(
            name='FilterTypeDescrip5',
        ),
        migrations.DeleteModel(
            name='FilterTypeDescrip6',
        ),
        migrations.DeleteModel(
            name='FilterTypeDescrip7',
        ),
    ]
