# Generated by Django 5.2.8 on 2026-05-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0109_delete_filtertypedescrip_delete_filtertypedescrip2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterequiptype',
            name='typeid',
        ),
    ]
