# Generated by Django 5.2.8 on 2026-05-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0110_remove_filterequiptype_typeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='jobtype1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobtype1', to='mhadatabase.filterequiptype', to_field='typeequip', verbose_name='jobtype1'),
        ),
    ]
