# Generated by Django 5.2.8 on 2026-05-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0112_alter_bidding_jobtype1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='jobtype1',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
    ]
