# Generated by Django 5.2.8 on 2026-05-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0116_alter_bidding_jobtype2_alter_bidding_jobtype3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='types',
            field=models.CharField(default=None, max_length=45, unique=True, verbose_name=''),
        ),
    ]
