# Generated by Django 5.2.8 on 2026-05-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0117_alter_type_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='types',
            field=models.CharField(default='', max_length=45, unique=True, verbose_name=''),
        ),
    ]
