# Generated by Django 5.2.8 on 2026-05-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0119_alter_type_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='jobtype2b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype3b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype4b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype5b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype6b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype7b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
    ]
