# Generated by Django 5.2.8 on 2026-05-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0120_alter_bidding_jobtype2b_alter_bidding_jobtype3b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript2b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript3b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript4b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript5b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript6b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript7b',
            field=models.CharField(blank=True, default=1, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype1b',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype2b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype3b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype4b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype5b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype6b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype7b',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=''),
        ),
    ]
