# Generated by Django 5.2.8 on 2026-05-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0121_alter_bidding_descript2b_alter_bidding_descript3b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipselection',
            name='addthermostat',
            field=models.CharField(blank=True, default='Yes', max_length=4, null=True, verbose_name=''),
        ),
    ]
