# Generated by Django 5.2.8 on 2026-05-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0122_alter_equipselection_addthermostat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebateinfo',
            name='furntherm96',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
