# Generated by Django 5.2.8 on 2026-05-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0123_rebateinfo_furntherm96'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebateinfo',
            name='furn96',
            field=models.IntegerField(default=None, null=True, verbose_name=''),
        ),
    ]
