# Generated by Django 5.2.8 on 2026-05-27 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0124_rebateinfo_furn96'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='jobtype1',
            field=models.ForeignKey(blank=True, default='Select Equip. Type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobtype1', to='mhadatabase.type', to_field='types', verbose_name='jobtype1'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype2',
            field=models.ForeignKey(blank=True, default='Select Equip. Type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobtype2', to='mhadatabase.type', to_field='types', verbose_name='jobtype2'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype3',
            field=models.ForeignKey(blank=True, default='Select Equip. Type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobtype3', to='mhadatabase.type', to_field='types', verbose_name='jobtype3'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype4',
            field=models.ForeignKey(blank=True, default='Select Equip. Type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobtype4', to='mhadatabase.type', to_field='types', verbose_name='jobtype4'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype5',
            field=models.ForeignKey(blank=True, default='Select Equip. Type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobtype5', to='mhadatabase.type', to_field='types', verbose_name='jobtype5'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype6',
            field=models.ForeignKey(blank=True, default='Select Equip. Type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobtype6', to='mhadatabase.type', to_field='types', verbose_name='jobtype6'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='jobtype7',
            field=models.ForeignKey(blank=True, default='Select Equip. Type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobtype7', to='mhadatabase.type', to_field='types', verbose_name='jobtype7'),
        ),
    ]
