# Generated by Django 5.2.8 on 2026-05-27 01:57

import django.db.models.deletion
import mhadatabase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0125_alter_bidding_jobtype1_alter_bidding_jobtype2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript1',
            field=models.ForeignKey(blank=True, default='Select Equipment', limit_choices_to=mhadatabase.models.limit_descript1b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript1', to='mhadatabase.equipment2', to_field='modelnum', verbose_name='Descript1'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript2',
            field=models.ForeignKey(blank=True, default='Select Equipment', limit_choices_to=mhadatabase.models.limit_descript2b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript2', to='mhadatabase.equipment2', to_field='modelnum', verbose_name='Descript2'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript3',
            field=models.ForeignKey(blank=True, default='Select Equipment', limit_choices_to=mhadatabase.models.limit_descript3b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript3', to='mhadatabase.equipment2', to_field='modelnum', verbose_name='Descript3'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript4',
            field=models.ForeignKey(blank=True, default='Select Equipment', limit_choices_to=mhadatabase.models.limit_descript4b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript4', to='mhadatabase.equipment2', to_field='modelnum', verbose_name='Descript4'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript5',
            field=models.ForeignKey(blank=True, default='Select Equipment', limit_choices_to=mhadatabase.models.limit_descript5b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript5', to='mhadatabase.equipment2', to_field='modelnum', verbose_name='Descript5'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript6',
            field=models.ForeignKey(blank=True, default='Select Equipment', limit_choices_to=mhadatabase.models.limit_descript6b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript6', to='mhadatabase.equipment2', to_field='modelnum', verbose_name='Descript6'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript7',
            field=models.ForeignKey(blank=True, default='Select Equipment', limit_choices_to=mhadatabase.models.limit_descript7b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript7', to='mhadatabase.equipment2', to_field='modelnum', verbose_name=''),
        ),
    ]
