# Generated by Django 5.2.8 on 2026-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0126_alter_bidding_descript1_alter_bidding_descript2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='descript19b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript20b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bidding',
            name='descript21b',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
    ]
