# Generated by Django 5.2.8 on 2026-05-27 16:39

import django.db.models.deletion
import mhadatabase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0127_bidding_descript19b_bidding_descript20b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='descript19',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript19b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript19', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript20',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript20b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript20', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='descript21',
            field=models.ForeignKey(blank=True, default='Select Material', limit_choices_to=mhadatabase.models.limit_descript21b_choices, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descript21', to='mhadatabase.material', to_field='descrip', verbose_name=''),
        ),
    ]
