# Generated by Django 5.2.8 on 2026-05-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0128_alter_bidding_descript19_alter_bidding_descript20_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techhours',
            name='hrstech',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, unique=True, verbose_name=''),
        ),
    ]
