# Generated by Django 5.2.8 on 2026-05-27 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0129_alter_techhours_hrstech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='techhrs',
            field=models.ForeignKey(blank=True, default='Hours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='techhrs', to='mhadatabase.techhours', to_field='hrstech', verbose_name=''),
        ),
    ]
