# Generated by Django 5.2.8 on 2026-05-27 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0132_alter_bidding_techhrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='techhrs2',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='techhrs2', to='mhadatabase.techhours', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='techhrs3',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='techhrs3', to='mhadatabase.techhours', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='techhrs4',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='techhrs4', to='mhadatabase.techhours', verbose_name=''),
        ),
    ]
