# Generated by Django 5.2.8 on 2026-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0133_alter_bidding_techhrs2_alter_bidding_techhrs3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techlevel',
            name='idA',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
