# Generated by Django 5.2.8 on 2026-06-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0134_techlevel_ida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
