# Generated by Django 5.2.8 on 2026-06-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0135_alter_contract_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='date',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
