# Generated by Django 5.2.8 on 2026-06-20 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhadatabase', '0136_remove_contract_date_alter_contract_contractdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
