from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView

app_name = "mhadatabase"
urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('mha', LoginView.as_view(template_name='mha/welcome.html'), name='mha'),
    path('main/', views.main, name='main'),
    path('mha/', views.welcome, name='mha'),
    path('', views.PostsListView.as_view(), name='export'),
    #    path('export/', views.PostsListView, name='export'),
    path('installbidingpage/', views.installbidingpage, name='installbidingpage'),
    path('equipmat/', views.equipmat, name='equipmat'),
    path('openequip/', views.openequip, name='openequip'),
    path('addnewequip/', views.addnewequip, name='addnewequip'),
    path('addnewequip2/', views.addnewequip2, name='addnewequip2'),
    path('addnewequip1/', views.addnewequip1, name='addnewequip1'),
    path('model/', views.model, name='model'),
    path('load_model/', views.load_model, name='load_model'),
    path('load_model2/', views.load_model2, name='load_model2'),
    #    path('mfg/', views.mfg, name='mfg'),
    #    path('mfg2/', views.mfg2, name='mfg2'),
    path('load_mfg/', views.load_mfg, name='load_mfg'),
    #    path('load_mfg2/', views.load_mfg2, name='load_mfg2'),
    path('mfg/', views.mfg, name='mfg'),
    path('mfg22/', views.mfg22, name='mfg22'),
    path('load_mfg2/', views.load_mfg2, name='load_mfg2'),
    path('smart/', views.smart, name='smart'),
    path('notsmart/', views.notsmart, name='notsmart'),
    path('type/', views.type, name='type'),
    path('type2/', views.type2, name='type2'),
    path('load_type2/', views.load_type2, name='load_type2'),
    path('load_type/', views.load_type, name='load_type'),

    path('config/', views.config, name='config'),
    path('config2/', views.config2, name='config2'),
#    path('config2cond/', views.config2cond, name='config2cond'),
#    path('config2evap/', views.config2evap, name='config2evap'),
    path('load_config/', views.load_config, name='load_config'),
    path('load_config2/', views.load_config2, name='load_config2'),
#    path('load_configfurn2/', views.load_configfurn2, name='load_configfurn2'),
#    path('load_configcond2/', views.load_configcond2, name='load_configcond2'),
#    path('load_configevap2/', views.load_configevap2, name='load_configevap2'),
    path('load_configtherm2/', views.load_configtherm2, name='load_configtherm2'),

    path('eff/', views.eff, name='eff'),
    path('eff2/', views.eff2, name='eff2'),
    path('load_eff/', views.load_eff, name='load_eff'),
#    path('eff2furn/', views.eff2furn, name='eff2furn'),
#    path('eff2cond/', views.eff2cond, name='eff2cond'),
#    path('eff2evap/', views.eff2evap, name='eff2evap'),
#    path('load_efffurn/', views.load_efffurn, name='load_efffurn'),
#    path('load_effcond/', views.load_effcond, name='load_effcond'),
#    path('load_effevap/', views.load_effevap, name='load_effevap'),

    path('load_eff2/', views.load_eff2, name='load_eff2'),
#    path('load_furneff2/', views.load_furneff2, name='load_furneff2'),
#    path('load_condeff2/', views.load_condeff2, name='load_condeff2'),
#    path('load_evapeff2/', views.load_evapeff2, name='load_evapeff2'),
    path('load_thermeff2/', views.load_thermeff2, name='load_thermeff2'),


    path('mfgmodeldescrip/', views.mfgmodeldescrip, name='mfgmodeldescrip'),
    path('mfgmodeldescrip2/', views.mfgmodeldescrip2, name='mfgmodeldescrip2'),
#    path('mfgmodeldescrip2cond/', views.mfgmodeldescrip2cond, name='mfgmodeldescrip2cond'),
#    path('mfgmodeldescrip2evap/', views.mfgmodeldescrip2evap, name='mfgmodeldescrip2evap'),
#    path('mfgmodeldescrip2therm/', views.mfgmodeldescrip2therm, name='mfgmodeldescrip2therm'),
#    path('load_mfgmodeldescripfurn/', views.load_mfgmodeldescripfurn, name='load_mfgmodeldescripfurn'),
#    path('load_mfgmodeldescripcond/', views.load_mfgmodeldescripcond, name='load_mfgmodeldescripcond'),
#    path('load_mfgmodeldescripevap/', views.load_mfgmodeldescripevap, name='load_mfgmodeldescripevap'),
#    path('load_mfgmodeldescriptherm/', views.load_mfgmodeldescriptherm, name='load_mfgmodeldescriptherm'),
    path('load_mfgmodeldescrip/', views.load_mfgmodeldescrip, name='load_mfgmodeldescrip'),
    path('load_mfgmodeldescrip2/', views.load_mfgmodeldescrip2, name='load_mfgmodeldescrip2'),
#    path('load_condmfgmodeldescrip2/', views.load_condmfgmodeldescrip2, name='load_condmfgmodeldescrip2'),
#    path('load_evapmfgmodeldescrip2/', views.load_evapmfgmodeldescrip2, name='load_evapmfgmodeldescrip2'),
#    path('load_thermmfgmodeldescrip2/', views.load_thermmfgmodeldescrip2, name='load_thermmfgmodeldescrip2'),

    path('gasviv/', views.gasviv, name='gasviv'),
    path('gasviv2/', views.gasviv2, name='gasviv2'),
#    path('load_gasvivfurn/', views.load_gasvivfurn, name='load_gasvivfurn'),
    path('load_gasviv/', views.load_gasviv, name='load_gasviv'),
    path('load_gasviv2/', views.load_gasviv2, name='load_gasviv2'),
#    path('load_condgasviv2/', views.load_condgasviv2, name='load_condgasviv2'),
#    path('load_evapgasviv2/', views.load_evapgasviv2, name='load_evapgasviv2'),
#    path('load_thermgasviv2/', views.load_thermgasviv2, name='load_thermgasviv2'),



    path('motortype/', views.motortype, name='motortype'),
    path('motortype2/', views.motortype2, name='motortype2'),
#    path('load_motortypefurn/', views.load_motortypefurn, name='load_motortypefurn'),
    path('load_motortype/', views.load_motortype, name='load_motortype'),
    path('load_motortype2/', views.load_motortype2, name='load_motortype2'),
#    path('load_condmotortype2/', views.load_condmotortype2, name='load_condmotortype2'),
#    path('load_evapmotortype2/', views.load_evapmotortype2, name='load_evapmotortype2'),
#    path('load_Thermmotortype2/', views.load_Thermmotortype2, name='load_Thermmotortype2'),

    path('description/', views.description, name='description'),
    path('description2/', views.description2, name='description2'),
#    path('description2cond/', views.description2cond, name='description2cond'),
#    path('description2evap/', views.description2evap, name='description2evap'),
#    path('description2therm/', views.description2therm, name='description2therm'),
    path('load_description2/', views.load_description2, name='load_description2'),
#    path('load_descriptioncond/', views.load_descriptioncond, name='load_descriptioncond'),
#    path('load_descriptionevap/', views.load_descriptionevap, name='load_descriptionevap'),
#    path('load_descriptiontherm/', views.load_descriptiontherm, name='load_descriptiontherm'),
    path('load_description/', views.load_description, name='load_description'),
#    path('load_furndescription2/', views.load_furndescription2, name='load_furndescription2'),
#    path('load_conddescription2/', views.load_conddescription2, name='load_conddescription2'),
#    path('load_evapdescription2/', views.load_evapdescription2, name='load_evapdescription2'),
#    path('load_thermdescription2/', views.load_thermdescription2, name='load_thermdescription2'),

    path('refrig/', views.refrig, name='refrig'),
    path('refrig2/', views.refrig2, name='refrig2'),
#    path('refrig2cond/', views.refrig2cond, name='refrig2cond'),
#    path('refrig2evap/', views.refrig2evap, name='refrig2evap'),
#    path('load_refrig/', views.load_refrig, name='load_refrig'),
#    path('load_refrigcond/', views.load_refrigcond, name='load_refrigcond'),
#    path('load_refrigevap/', views.load_refrigevap, name='load_refrigevap'),
    path('load_refrig/', views.load_refrig, name='load_refrig'),
    path('load_refrig2/', views.load_refrig2, name='load_refrig2'),
#    path('load_condrefrig2/', views.load_condrefrig2, name='load_condrefrig2'),
#    path('load_evaprefrig2/', views.load_evaprefrig2, name='load_evaprefrig2'),
#    path('load_Thermrefrig2/', views.load_Thermrefrig2, name='load_Thermrefrig2'),

    path('btu/', views.btu, name='btu'),
    path('btu2/', views.btu2, name='btu2'),
#    path('btu2cond/', views.btu2cond, name='btu2cond'),
#    path('load_btufurn/', views.load_btufurn, name='load_btufurn'),
#    path('load_btucond/', views.load_btucond, name='load_btucond'),
#    path('load_btuevap/', views.load_btuevap, name='load_btuevap'),

#    path('btu2evap/', views.btu2evap, name='btu2evap'),



    path('load_btu/', views.load_btu, name='load_btu'),
    path('load_btu2/', views.load_btu2, name='load_btu2'),
#    path('load_condbtu2/', views.load_condbtu2, name='load_condbtu2'),
#    path('load_evapbtu2/', views.load_evapbtu2, name='load_evapbtu2'),
#    path('load_thermbtu2/', views.load_thermbtu2, name='load_thermbtu2'),

    path('outputstg1/', views.outputstg1, name='outputstg1'),
    path('outputstg12/', views.outputstg12, name='outputstg12'),
#    path('load_outputstg1furn/', views.load_outputstg1furn, name='load_outputstg1furn'),
    path('load_outputstg1/', views.load_outputstg1, name='load_outputstg1'),
    path('load_outputstg12/', views.load_outputstg12, name='load_outputstg12'),
#    path('load_condoutputstg12/', views.load_condoutputstg12, name='load_condoutputstg12'),
#    path('load_evapoutputstg12/', views.load_evapoutputstg12, name='load_evapoutputstg12'),
#    path('load_thermoutputstg12/', views.load_thermoutputstg12, name='load_thermoutputstg12'),

    path('outputstg2/', views.outputstg2, name='outputstg2'),
    path('outputstg22/', views.outputstg22, name='outputstg22'),
    path('load_outputstg22/', views.load_outputstg22, name='load_outputstg22'),
    path('load_outputstg2/', views.load_outputstg2, name='load_outputstg2'),
#    path('load_furnoutputstg22/', views.load_furnoutputstg22, name='load_furnoutputstg22'),
#    path('load_condoutputstg22/', views.load_condoutputstg22, name='load_condoutputstg22'),
#    path('load_evapoutputstg22/', views.load_evapoutputstg22, name='load_evapoutputstg22'),
#    path('load_thermoutputstg22/', views.load_thermoutputstg22, name='load_thermoutputstg22'),

    path('outputstg3/', views.outputstg3, name='outputstg3'),
    path('outputstg32/', views.outputstg32, name='outputstg32'),
    path('load_outputstg32/', views.load_outputstg32, name='load_outputstg32'),
    path('load_outputstg3/', views.load_outputstg3, name='load_outputstg3'),
#    path('load_furnoutputstg32/', views.load_furnoutputstg32, name='load_furnoutputstg32'),
#    path('load_condoutputstg32/', views.load_condoutputstg32, name='load_condoutputstg32'),
#    path('load_evapoutputstg32/', views.load_evapoutputstg32, name='load_evapoutputstg32'),
#    path('load_thermoutputstg32/', views.load_thermoutputstg32, name='load_thermoutputstg32'),


    path('<path:modelnum>/load_motortypeedit/', views.load_motortypeedit, name='load_motortypeedit'),
    path('<path:modelnum>/load_refrigedit/', views.load_refrigedit, name='load_refrigedit'),

    path('<path:modelnum>/load_btuedit/', views.load_btuedit, name='load_btuedit'),

    path('<path:modelnum>/load_2model/', views.load_2model, name='load_2model'),
    path('<path:modelnum>/load_2config/', views.load_2config, name='load_2config'),
    path('<path:modelnum>/load_2cost/', views.load_2cost, name='load_2cost'),
    path('<path:modelnum>/load_2height/', views.load_2height, name='load_2height'),
    path('<path:modelnum>/load_2width/', views.load_2width, name='load_2width'),
    path('<path:modelnum>/load_2depth/', views.load_2depth, name='load_2depth'),
    path('<path:modelnum>/load_2warr/', views.load_2warr, name='load_2warr'),

    path('<path:id>/costedit/', views.costedit, name='costedit'),
    path('<path:id>/heightedit/', views.heightedit, name='heightedit'),
    path('<path:id>/widthedit/', views.widthedit, name='widthedit'),
    path('<path:id>/depthedit/', views.depthedit, name='depthedit'),
    path('<path:id>/deleteeditequip/', views.deleteeditequip, name='deleteeditequip'),

    path('<path:id>/smarttherm/', views.smarttherm, name='smarttherm'),




    path('cost/', views.cost, name='cost'),
    path('costA/', views.costA, name='costA'),
    path('cost2/', views.cost2, name='cost2'),
    path('load_cost/', views.load_cost, name='load_cost'),
    path('load_cost2/', views.load_cost2, name='load_cost2'),
    path('load_cost3/', views.load_cost3, name='load_cost3'),
    path('<path:id>/load_costedit/', views.load_costedit, name='load_costedit'),

    path('<path:id>/load_costedit2/', views.load_costedit2, name='load_costedit2'),


    path('<path:id>/load_coilheightedit/', views.load_coilheightedit, name='load_coilheightedit'),
    path('<path:id>/load_coilwidthedit/', views.load_coilwidthedit, name='load_coilwidthedit'),
    path('<path:id>/load_coildepthedit/', views.load_coildepthedit, name='load_coildepthedit'),






    path('<path:modelnum>/warredit/', views.warredit, name='warredit'),
    path('warr/', views.warr, name='warr'),
    path('warrA/', views.warrA, name='warrA'),
    path('warr2/', views.warr2, name='warr2'),
    path('warr3/', views.warr3, name='warr3'),
    path('load_warr/', views.load_warr, name='load_warr'),
    path('load_warr2/', views.load_warr2, name='load_warr2'),
    path('load_addnew/', views.load_addnew, name='load_addnew'),
    path('addnew2/', views.addnew2, name='addnew2'),
    path('height/', views.height, name='height'),
    path('heightA/', views.heightA, name='heightA'),
    path('load_height/', views.load_height, name='load_height'),
    path('load_height2/', views.load_height2, name='load_height2'),
    path('width/', views.width, name='width'),
    path('widthA/', views.widthA, name='widthA'),
    path('load_width/', views.load_width, name='load_width'),
    path('load_width2/', views.load_width2, name='load_width2'),
    path('depth/', views.depth, name='depth'),
    path('depthA/', views.depthA, name='depthA'),
    path('load_depth/', views.load_depth, name='load_depth'),
    path('load_depth2/', views.load_depth2, name='load_depth2'),
    path('deleteequip/', views.deleteequip, name='deleteequip'),
    path('updateequip/', views.updateequip, name='updateequip'),
    path('modequip/', views.modequip, name='modequip'),
    path('typeupdate/', views.typeupdate, name='typeupdate'),
    path('load_typeupdate/', views.load_typeupdate, name='load_typeupdate'),
    path('mfgupdate/', views.mfgupdate, name='mfgupdate'),
    path('modnumupdate/', views.modnumupdate, name='modnumupdate'),
    path('furncoilheight/', views.furncoilheight, name='furncoilheight'),



    path('mfgupdateload/', views.mfgupdateload, name='mfgupdateload'),
    path('load_mfgupdate/', views.load_mfgupdate, name='load_mfgupdate'),
    path('load_mfgupdate2/', views.load_mfgupdate2, name='load_mfgupdate2'),
    path('effupdate/', views.effupdate, name='effupdate'),
    path('effupdateload/', views.effupdateload, name='effupdateload'),
    path('load_efficiencyupdatefurn/', views.load_efficiencyupdatefurn, name='load_efficiencyupdatefurn'),

    path('mfgmodeldescripload/', views.mfgmodeldescripload, name='mfgmodeldescripload'),

    path('efficiencyupdatecond/', views.efficiencyupdatecond, name='efficiencyupdatecond'),
    path('load_efficiencyupdatecond/', views.load_efficiencyupdatecond, name='load_efficiencyupdatecond'),

    path('load_efficiencyupdatefurn2/', views.load_efficiencyupdatefurn2, name='load_efficiencyupdatefurn2'),
    path('load_efficiencyupdatecond2/', views.load_efficiencyupdatecond2, name='load_efficiencyupdatecond2'),
    path('modeldescripupdate/', views.modeldescripupdate, name='modeldescripupdate'),
    path('load_modeldescripupdate/', views.load_modeldescripupdate, name='load_modeldescripupdate'),
    path('load_modeldescripupdate2/', views.load_modeldescripupdate2, name='load_modeldescripupdate2'),

    path('modeldescripupdatecond/', views.modeldescripupdatecond, name='modeldescripupdatecond'),
    path('load_modeldescripupdatecond/', views.load_modeldescripupdatecond, name='load_modeldescripupdatecond'),
    path('load_modeldescripupdatecond2/', views.load_modeldescripupdatecond2, name='load_modeldescripupdatecond2'),

    path('configupdate/', views.configupdate, name='configupdate'),
    path('load_configupdate/', views.load_configupdate, name='load_configupdate'),
    path('update1/', views.update1, name='update1'),
    path('update2/', views.update2, name='update2'),
    path('update3/', views.update3, name='update3'),

    path('update5/', views.update5, name='update5'),

    path('update4/', views.update4, name='update4'),
    path('filtermodelnum/', views.filtermodelnum, name='filtermodelnum'),


    path('<path:id>/editquip/', views.editquip, name='editquip'),
    path('<path:modelnum>/editquip2/', views.editquip2, name='editquip2'),
    path('<path:modelnum>/editfurnequip/', views.editfurnequip, name='editfurnequip'),
    #    path('furnglobalincrease1/', views.furnglobalincrease1, name='furnglobalincrease1'),
    path('globalincrease1/', views.furnglobalincrease1, name='furnglobalincrease1'),
    path('globalincrease2/', views.globalincrease2, name='globalincrease2'),
    path('globalincrease3/', views.globalincrease3, name='globalincrease3'),
    path('globalincrease4/', views.globalincrease4, name='globalincrease4'),
    path('globalincrease5/', views.globalincrease5, name='globalincrease5'),
    path('percentincrease1/', views.percentincrease1, name='percentincrease1'),
    path('percentincrease2/', views.percentincrease2, name='percentincrease2'),
    path('percentincrease3/', views.percentincrease3, name='percentincrease3'),
    path('percentincrease4/', views.percentincrease4, name='percentincrease4'),
    path('percentincrease5/', views.percentincrease5, name='percentincrease5'),
    path('updateprice1/', views.updateprice1, name='updateprice1'),
    path('updateprice2/', views.updateprice2, name='updateprice2'),
    path('updateprice3/', views.updateprice3, name='updateprice3'),
    path('updateprice4/', views.updateprice4, name='updateprice4'),
    path('updateprice5/', views.updateprice5, name='updateprice5'),
    path('mattoupdate/', views.mattoupdate, name='mattoupdate'),
    path('addnewmat/', views.addnewmat, name='addnewmat'),
    path('adddescrip/', views.adddescrip, name='adddescrip'),
    path('cost/', views.cost, name='cost'),
    path('addcost/', views.addcost, name='addcost'),
    path('addmatmfg/', views.addmatmfg, name='addmatmfg'),
    path('matmfg2/', views.matmfg2, name='matmfg2'),
    path('load_matmfg2/', views.load_matmfg2, name='load_matmfg2'),
    path('matvendor/', views.matvendor, name='matvendor'),
    path('matvendor2/', views.matvendor2, name='matvendor2'),
    path('load_matvendor2/', views.load_matvendor2, name='load_matvendor2'),
    path('vendornum/', views.vendornum, name='vendornum'),
    path('mattype/', views.mattype, name='mattype'),
    path('mattype2/', views.mattype2, name='mattype2'),
    path('load_mattype2/', views.load_mattype2, name='load_mattype2'),
    path('deletemat/', views.deletemat, name='deletemat'),
    path('<int:idA>/deletemat1/', views.deletemat1, name='deletemat1'),
    path('matsearch/', views.matsearch, name='matsearch'),
    path('filtermfg/', views.filtermfg, name='filtermfg'),
    path('filtervendor/', views.filtervendor, name='filtervendor'),
    path('filtertype/', views.filtertype, name='filtertype'),
    path('mfgsearch/', views.mfgsearch, name='mfgsearch'),
    path('vendorsearch/', views.vendorsearch, name='vendorsearch'),
    path('typesearch/', views.typesearch, name='typesearch'),
    path('<int:idA>/editmat/', views.editmat, name='editmat'),
    path('<int:idA>/costmat/', views.costmat, name='costmat'),
    path('<int:idA>/matcostload/', views.matcostload, name='matcostload'),
    path('<int:idA>/mfgmat/', views.mfgmat, name='mfgmat'),
    path('<int:idA>/matmfgload/', views.matmfgload, name='matmfgload'),
    path('<int:idA>/mfgvendor/', views.mfgvendor, name='mfgvendor'),
    path('<int:idA>/matvendorload/', views.matvendorload, name='matvendorload'),
    path('<int:idA>/mfgvennum/', views.mfgvennum, name='mfgvennum'),
    path('<int:idA>/matvennumload/', views.matvennumload, name='matvennumload'),
    path('<int:idA>/mfgtype/', views.mfgtype, name='mfgtype'),
    path('<int:idA>/mattypeload/', views.mattypeload, name='mattypeload'),
    path('customer/', views.customer, name='customer'),
    path('newcon/', views.newcon, name='newcon'),

    path('<int:id>/addnewproject/', views.addnewproject, name='addnewproject'),

    path('conerror', views.conerror, name='conerror'),
    path('custerror', views.custerror, name='custerror'),
    path('<int:id>/dupconinfo/', views.dupconinfo, name='dupconinfo'),
    path('<int:id>/newcust/', views.newcust, name='newcust'),
    path('<int:id>/deletecon/', views.deletecon, name='deletecon'),
    path('<int:id>/deletecust/', views.deletecust, name='deletecust'),

    path('<int:id>/jobselection/', views.jobselection, name='jobselection'),
    path('<int:bidid>/jobselection2/', views.jobselection2, name='jobselection2'),
    path('<int:bidid>/jobselection3/', views.jobselection3, name='jobselection3'),
    path('<int:bidid>/jobselection4/', views.jobselection4, name='jobselection4'),
    path('<int:bidid>/jobselection5/', views.jobselection5, name='jobselection5'),
    path('<int:id>/contractorpage/', views.contractorpage, name='contractorpage'),
 #   path('<int:custid>/customerinfo/', views.customerinfo, name='customerinfo'),
    path('<int:jobid>/customerinfo/', views.customerinfo, name='customerinfo'),
    path('<int:id>/customerpage/', views.customerpage, name='customerpage'),
    path('<int:id>/addcust/', views.addcust, name='addcust'),
    path('<int:id>/conedit/', views.conedit, name='conedit'),
    path('<int:id>/custedit/', views.custedit, name='custedit'),
    path('<int:custid>/yesdupcon/', views.yesdupcon, name='yesdupcon'),
    path('con_info_existing', views.con_info_existing, name='con_info_existing'),
    path('cust_info_existing', views.cust_info_existing, name='cust_info_existing'),
    path('custcompany', views.custcompany, name='custcompany'),
    path('<int:id>/addcustconfirm/', views.addcustconfirm, name='addcustconfirm'),
    path('<int:id>/addnewcust/', views.addnewcust, name='addnewcust'),
    path('<int:id>/equipselection1/', views.equipselection1, name='equipselection1'),
    path('<int:id>/equipselection2/', views.equipselection2, name='equipselection2'),
    path('<int:id>/equipselection3/', views.equipselection3, name='equipselection3'),
    path('<int:id>/equipselection4/', views.equipselection4, name='equipselection4'), 
    path('<int:id>/equipselection5/', views.equipselection5, name='equipselection5'),
    path('<int:id>/equipselection2A/', views.equipselection2A, name='equipselection2A'),
    path('<int:id>/equipselection2AB/', views.equipselection2AB, name='equipselection2AB'),
    path('<int:id>/equipselection2AC/', views.equipselection2AC, name='equipselection2AC'),
    path('<int:id>/equipselection2AD/', views.equipselection2AD, name='equipselection2AD'),
    path('<int:id>/equipselection2AE/', views.equipselection2AE, name='equipselection2AE'),
    path('<int:id>/equipselection3A/', views.equipselection3A, name='equipselection3A'),
    path('<int:id>/equipselection4A/', views.equipselection4A, name='equipselection4A'),
    path('<int:id>/equipselection5A/', views.equipselection5A, name='equipselection5A'),
    path('<int:id>/equipselection6A/', views.equipselection6A, name='equipselection6A'),
    path('<int:id>/equipselection2B/', views.equipselection2B, name='equipselection2B'),
    path('<int:id>/equipselection3B/', views.equipselection3B, name='equipselection3B'),
    path('<int:id>/equipselection4B/', views.equipselection4B, name='equipselection4B'),
    path('<int:id>/equipselection5B/', views.equipselection5B, name='equipselection5B'),
    path('<int:id>/equipselection6B/', views.equipselection6B, name='equipselection6B'),

    path('<int:id>/equipselection2C/', views.equipselection2C, name='equipselection2C'),
    path('<int:id>/equipselection3C/', views.equipselection3C, name='equipselection3C'),
    path('<int:id>/equipselection4C/', views.equipselection4C, name='equipselection4C'),
    path('<int:id>/equipselection5C/', views.equipselection5C, name='equipselection5C'),
    path('<int:id>/equipselection6C/', views.equipselection6C, name='equipselection6C'),



    path('joblocation', views.joblocation, name='joblocation'),
    path('airhandler', views.airhandler, name='airhandler'),
    path('airhandler3a', views.airhandler3a, name='airhandler3a'),

    path('outsideunit', views.outsideunit, name='outsideunit'),
    path('load_condeff', views.load_condeff, name='load_condeff'),
    path('condeff', views.condeff, name='condeff'),
    path('load_condbtu', views.load_condbtu, name='load_condbtu'),
    path('condbtu', views.condbtu, name='condbtu'),
    path('load_conddescript', views.load_conddescript, name='load_conddescript'),
    path('conddescrip', views.conddescrip, name='conddescrip'),
    path('load_condmodnum', views.load_condmodnum, name='load_condmodnum'),
    path('condmodnum', views.condmodnum, name='condmodnum'),
    path('load_furnbtu', views.load_furnbtu, name='load_furnbtu'),
    path('furnbtu', views.furnbtu, name='furnbtu'),
    path('furnbtu3a', views.furnbtu3a, name='furnbtu3a'),
    path('load_furnconfig', views.load_furnconfig, name='load_furnconfig'),
    path('load_furnconfig2', views.load_furnconfig2, name='load_furnconfig2'),
    path('furnconfig3a', views.furnconfig3a, name='furnconfig3a'),
    path('furnconfig', views.furnconfig, name='furnconfig'),
    path('load_furneff', views.load_furneff, name='load_furneff'),
    path('furneff', views.furneff, name='furneff'),
    path('furneff3a', views.furneff3a, name='furneff3a'),
    path('load_furndescript', views.load_furndescript, name='load_furndescript'),
    path('load_furndescript3a', views.load_furndescript3a, name='load_furndescript3a'),
    path('furndescript', views.furndescript, name='furndescript'),
    path('furndescript3a', views.furndescript3a, name='furndescript3a'),
    path('load_furnmodnum', views.load_furnmodnum, name='load_furnmodnum'),
    path('furnmodnum', views.furnmodnum, name='furnmodnum'),
    path('furnmodnum3a', views.furnmodnum3a, name='furnmodnum3a'),
    path('furnmodnum2up', views.furnmodnum2up, name='furnmodnum2up'),
    path('furnmodnum2down', views.furnmodnum2down, name='furnmodnum2down'),
    path('furnmodnum2all', views.furnmodnum2all, name='furnmodnum2all'),
    path('furnmodnum2A', views.furnmodnum2A, name='furnmodnum2A'),
    path('load_furnconfig2A', views.load_furnconfig2A, name='load_furnconfig2A'),
    path('load_furnheight2A', views.load_furnheight2A, name='load_furnheight2A'),
    path('load_furnwidth2A', views.load_furnwidth2A, name='load_furnwidth2A'),
    path('load_furndepth2A', views.load_furndepth2A, name='load_furndepth2A'),
    path('condeff2A', views.condeff2A, name='condeff2A'),
    path('load_condbtu2A', views.load_condbtu2A, name='load_condbtu2A'),
    path('condbtu2A', views.condbtu2A, name='condbtu2A'),
    path('load_conddescript2A', views.load_conddescript2A, name='load_conddescript2A'),
    path('conddescrip2A', views.conddescrip2A, name='conddescrip2A'),
    path('load_condmodnum2A', views.load_condmodnum2A, name='load_condmodnum2A'),
    path('load_coilconfig2A', views.load_coilconfig2A, name='load_coilconfig2A'),
    path('coilconfig2up', views.coilconfig2up, name='coilconfig2up'),
    path('coilconfig2A', views.coilconfig2A, name='coilconfig2A'),
    path('load_coilbtu2A', views.load_coilbtu2A, name='load_coilbtu2A'),
    path('coilbtu2A', views.coilbtu2A, name='coilbtu2A'),
    path('load_coiltype2A', views.load_coiltype2A, name='load_coiltype2A'),
    path('coiltype2A', views.coiltype2A, name='coiltype2A'),
    path('load_coilmodnum2A', views.load_coilmodnum2A, name='load_coilmodnum2A'),

    path('load_coilheight2A', views.load_coilheight2A, name='load_coilheight2A'),
    path('load_coilwidth2A', views.load_coilwidth2A, name='load_coilwidth2A'),
    path('load_coildepth2A', views.load_coildepth2A, name='load_coildepth2A'),
    path('addthermostat2A', views.addthermostat2A, name='addthermostat2A'),
    path('addthermostat1', views.addthermostat1, name='addthermostat1'),
    path('addthermostat3A', views.addthermostat3A, name='addthermostat3A'),
    path('thermostatmodnum3an', views.thermostatmodnum3an, name='thermostatmodnum3an'),

    path('existfurnheight', views.existfurnheight, name='existfurnheight'),
    path('load_existfurnheight', views.load_existfurnheight, name='load_existfurnheight'),
    path('existfurnwidth', views.existfurnwidth, name='existfurnwidth'),
    path('existfurndepth', views.existfurndepth, name='existfurndepth'),
    path('existfurnconfig', views.existfurnconfig, name='existfurnconfig'),


    path('load_existfurndepth', views.load_existfurndepth, name='load_existfurndepth'),

    path('load_thermomfg', views.load_thermomfg, name='load_thermomfg'),
    path('thermomfg', views.thermomfg, name='thermomfg'),
    path('thermomfg3a', views.thermomfg3a, name='thermomfg3a'),
    path('thermomfg2a', views.thermomfg2a, name='thermomfg2a'),
    path('load_thermomodnum', views.load_thermomodnum, name='load_thermomodnum'),
    path('load_thermomodnum2a', views.load_thermomodnum2a, name='load_thermomodnum2a'),
    path('thermostatmodnum', views.thermostatmodnum, name='thermostatmodnum'),
    path('thermostatmodnum3a', views.thermostatmodnum3a, name='thermostatmodnum3a'),
    path('thermostatmodnum3an', views.thermostatmodnum3an, name='thermostatmodnum3an'),
    path('thermostatmodnum2a', views.thermostatmodnum2a, name='thermostatmodnum2a'),
    path('load_furnheight', views.load_furnheight, name='load_furnheight'),
    path('load_furnwidth', views.load_furnwidth, name='load_furnwidth'),
    path('load_furnwidth2', views.load_furnwidth2, name='load_furnwidth2'),
    path('load_furndepth', views.load_furndepth, name='load_furndepth'),
    path('load_furndepth2', views.load_furndepth2, name='load_furndepth2'),
    path('coiltype', views.coiltype, name='coiltype'),
    path('load_coilbtu', views.load_coilbtu, name='load_coilbtu'),
    path('coilbtu', views.coilbtu, name='coilbtu'),
    path('load_coilconfig', views.load_coilconfig, name='load_coilconfig'),
    path('coilconfig', views.coilconfig, name='coilconfig'),
    path('load_coilmodnum', views.load_coilmodnum, name='load_coilmodnum'),
    path('coilmodnum', views.coilmodnum, name='coilmodnum'),
    path('load_coilheight', views.load_coilheight, name='load_coilheight'),
    path('load_coilwidth', views.load_coilwidth, name='load_coilwidth'),
    path('load_furncoilheight', views.load_furncoilheight, name='load_furncoilheight'),
    path('load_coiltype', views.load_coiltype, name='load_coiltype'),
    path('<path:id>/deleteediteequip/', views.deleteediteequip, name='deleteediteequip'),
    path('load_vendor1', views.load_vendor1, name='load_vendor1'),
    path('load_vendor2', views.load_vendor2, name='load_vendor2'),
    path('load_totalrebate', views.load_totalrebate, name='load_totalrebate'),
    path('deleteequipselection', views.deleteequipselection, name='deleteequipselection'),

    path('<int:bidid>/bidpage/', views.bidpage, name='bidpage'),



    path('<int:bidid>/jobcost/', views.jobcost, name='jobcost'),
    path('<int:bidid>/targetnet/', views.targetnet, name='targetnet'),
    path('<int:bidid>/cancelbid/', views.cancelbid, name='cancelbid'),

    path('<int:bidid>/bidpage1/', views.bidpage1, name='bidpage1'),
    path('<int:bidid>/bidpage2/', views.bidpage2, name='bidpage2'),
    path('<int:bidid>/bidpage3/', views.bidpage3, name='bidpage3'),
    path('<int:bidid>/bidpage4/', views.bidpage4, name='bidpage4'),
    path('<int:bidid>/bidpage5/', views.bidpage5, name='bidpage5'),

    path('<int:bidid>/load_tech2/', views.load_tech2, name='load_tech2'),
    path('<int:bidid>/load_tech3/', views.load_tech3, name='load_tech3'),
    path('<int:bidid>/load_tech4/', views.load_tech4, name='load_tech4'),

    path('<int:jobid>/addnewosr/', views.addnewosr, name='addnewosr'),
    path('<int:jobid>/newvendordescript/', views.newvendordescript, name='newvendordescript'),
    path('<int:jobid>/newvendorprice/', views.newvendorprice, name='newvendorprice'),
    path('<int:jobid>/newvendor/', views.newvendor, name='newvendor'),
    path('<int:jobid>/deletenewvendor/', views.deletenewvendor, name='deletenewvendor'),

    path('<int:bidid>/equipselection4A/', views.equipselection4A, name='equipselection4A'),

    path('<int:bidid>/jobtype1/', views.jobtype1, name='jobtype1'),
    path('<int:bidid>/load_jobtype1/', views.load_jobtype1, name='load_jobtype1'),
    path('<int:bidid>/descript1/', views.descript1, name='descript1'),
    path('<int:bidid>/load_descript1/', views.load_descript1, name='load_descript1'),
    path('<int:bidid>/load_descript1b/', views.load_descript1b, name='load_descript1b'),
    path('<int:bidid>/quant1/', views.quant1, name='quant1'),
    path('<int:bidid>/delete1/', views.delete1, name='delete1'),
    path('<int:bidid>/load_quanity1/', views.load_quanity1, name='load_quanity1'),

    path('<int:bidid>/jobtype2/', views.jobtype2, name='jobtype2'),
    path('<int:bidid>/load_jobtype2/', views.load_jobtype2, name='load_jobtype2'),
    path('<int:bidid>/descript2/', views.descript2, name='descript2'),
    path('<int:bidid>/load_descript2/', views.load_descript2, name='load_descript2'),
    path('<int:bidid>/load_descript2b/', views.load_descript2b, name='load_descript2b'),
    path('<int:bidid>/quant2/', views.quant2, name='quant2'),
    path('<int:bidid>/delete2/', views.delete2, name='delete2'),
    path('<int:bidid>/load_quanity2/', views.load_quanity2, name='load_quanity2'),

    path('<int:bidid>/jobtype3/', views.jobtype3, name='jobtype3'),
    path('<int:bidid>/load_jobtype3/', views.load_jobtype3, name='load_jobtype3'),
    path('<int:bidid>/descript3/', views.descript3, name='descript3'),
    path('<int:bidid>/load_descript3/', views.load_descript3, name='load_descript3'),
    path('<int:bidid>/load_descript3b/', views.load_descript3b, name='load_descript3b'),
    path('<int:bidid>/quant3/', views.quant3, name='quant3'),
    path('<int:bidid>/delete3/', views.delete3, name='delete3'),
    path('<int:bidid>/load_quanity3/', views.load_quanity3, name='load_quanity3'),

    path('<int:bidid>/jobtype4/', views.jobtype4, name='jobtype4'),
    path('<int:bidid>/load_jobtype4/', views.load_jobtype4, name='load_jobtype4'),
    path('<int:bidid>/descript4/', views.descript4, name='descript4'),
    path('<int:bidid>/load_descript4/', views.load_descript4, name='load_descript4'),
    path('<int:bidid>/load_descript4b/', views.load_descript4b, name='load_descript4b'),
    path('<int:bidid>/quant4/', views.quant4, name='quant4'),
    path('<int:bidid>/delete4/', views.delete4, name='delete4'),
    path('<int:bidid>/load_quanity4/', views.load_quanity4, name='load_quanity4'),

    path('<int:bidid>/jobtype5/', views.jobtype5, name='jobtype5'),
    path('<int:bidid>/load_jobtype5/', views.load_jobtype5, name='load_jobtype5'),
    path('<int:bidid>/descript5/', views.descript5, name='descript5'),
    path('<int:bidid>/load_descript5/', views.load_descript5, name='load_descript5'),
    path('<int:bidid>/load_descript5b/', views.load_descript5b, name='load_descript5b'),
    path('<int:bidid>/quant5/', views.quant5, name='quant5'),
    path('<int:bidid>/delete5/', views.delete5, name='delete5'),
    path('<int:bidid>/load_quanity5/', views.load_quanity5, name='load_quanity5'),

    path('<int:bidid>/jobtype6/', views.jobtype6, name='jobtype6'),
    path('<int:bidid>/load_jobtype6/', views.load_jobtype6, name='load_jobtype6'),
    path('<int:bidid>/descript6/', views.descript6, name='descript6'),
    path('<int:bidid>/load_descript6/', views.load_descript6, name='load_descript6'),
    path('<int:bidid>/load_descript6b/', views.load_descript6b, name='load_descript6b'),
    path('<int:bidid>/quant6/', views.quant6, name='quant6'),
    path('<int:bidid>/delete6/', views.delete6, name='delete6'),
    path('<int:bidid>/load_quanity6/', views.load_quanity6, name='load_quanity6'),

    path('<int:bidid>/jobtype7/', views.jobtype7, name='jobtype7'),
    path('<int:bidid>/load_jobtype7/', views.load_jobtype7, name='load_jobtype7'),
    path('<int:bidid>/descript7/', views.descript7, name='descript7'),
    path('<int:bidid>/load_descript7/', views.load_descript7, name='load_descript7'),
    path('<int:bidid>/load_descript7b/', views.load_descript7b, name='load_descript7b'),
    path('<int:bidid>/quant7/', views.quant7, name='quant7'),
    path('<int:bidid>/delete7/', views.delete7, name='delete7'),
    path('<int:bidid>/load_quanity7/', views.load_quanity7, name='load_quanity7'),

    path('<int:bidid>/descript8/', views.descript8, name='descript8'),
    path('<int:bidid>/load_descript8/', views.load_descript8, name='load_descript8'),
    path('<int:bidid>/load_descript8b/', views.load_descript8b, name='load_descript8b'),
    path('<int:bidid>/load_quanity8/', views.load_quanity8, name='load_quanity8'),
    path('<int:bidid>/quant8/', views.quant8, name='quant8'),
    path('<int:bidid>/delete8/', views.delete8, name='delete8'),

    path('<int:bidid>/descript9/', views.descript9, name='descript9'),
    path('<int:bidid>/load_descript9/', views.load_descript9, name='load_descript9'),
    path('<int:bidid>/load_quanity9/', views.load_quanity9, name='load_quanity9'),
    path('<int:bidid>/quant9/', views.quant9, name='quant9'),
    path('<int:bidid>/delete9/', views.delete9, name='delete9'),
    path('<int:bidid>/delete9a/', views.delete9a, name='delete9a'),

    path('<int:bidid>/delete10a/', views.delete10a, name='delete10a'),
    path('<int:bidid>/delete11a/', views.delete11a, name='delete11a'),
    path('<int:bidid>/delete12a/', views.delete12a, name='delete12a'),
    path('<int:bidid>/delete13a/', views.delete13a, name='delete13a'),
    path('<int:bidid>/delete14a/', views.delete14a, name='delete14a'),
    path('<int:bidid>/delete15a/', views.delete15a, name='delete15a'),
    path('<int:bidid>/delete16a/', views.delete16a, name='delete16a'),
    path('<int:bidid>/delete17a/', views.delete17a, name='delete17a'),
    path('<int:bidid>/delete18a/', views.delete18a, name='delete18a'),
    path('<int:bidid>/delete19a/', views.delete19a, name='delete19a'),
    path('<int:bidid>/delete20a/', views.delete20a, name='delete20a'),




    path('<int:bidid>/descript10/', views.descript10, name='descript10'),
    path('<int:bidid>/load_descript10/', views.load_descript10, name='load_descript10'),
    path('<int:bidid>/load_quanity10/', views.load_quanity10, name='load_quanity10'),
    path('<int:bidid>/quant10/', views.quant10, name='quant10'),
    path('<int:bidid>/delete10/', views.delete10, name='delete10'),

    path('<int:bidid>/descript11/', views.descript11, name='descript11'),
    path('<int:bidid>/load_descript11/', views.load_descript11, name='load_descript11'),
    path('<int:bidid>/load_quanity11/', views.load_quanity11, name='load_quanity11'),
    path('<int:bidid>/quant11/', views.quant11, name='quant11'),
    path('<int:bidid>/delete11/', views.delete11, name='delete11'),

    path('<int:bidid>/descript12/', views.descript12, name='descript12'),
    path('<int:bidid>/load_descript12/', views.load_descript12, name='load_descript12'),
    path('<int:bidid>/load_quanity12/', views.load_quanity12, name='load_quanity12'),
    path('<int:bidid>/quant12/', views.quant12, name='quant12'),
    path('<int:bidid>/delete12/', views.delete12, name='delete12'),

    path('<int:bidid>/descript13/', views.descript13, name='descript13'),
    path('<int:bidid>/load_descript13/', views.load_descript13, name='load_descript13'),
    path('<int:bidid>/load_quanity13/', views.load_quanity13, name='load_quanity13'),
    path('<int:bidid>/quant13/', views.quant13, name='quant13'),
    path('<int:bidid>/delete13/', views.delete13, name='delete13'),

    path('<int:bidid>/descript14/', views.descript14, name='descript14'),
    path('<int:bidid>/load_descript14/', views.load_descript14, name='load_descript14'),
    path('<int:bidid>/load_quanity14/', views.load_quanity14, name='load_quanity14'),
    path('<int:bidid>/quant14/', views.quant14, name='quant14'),
    path('<int:bidid>/delete14/', views.delete14, name='delete14'),

    path('<int:bidid>/descript15/', views.descript15, name='descript15'),
    path('<int:bidid>/load_descript15/', views.load_descript15, name='load_descript15'),
    path('<int:bidid>/load_quanity15/', views.load_quanity15, name='load_quanity15'),
    path('<int:bidid>/quant15/', views.quant15, name='quant15'),
    path('<int:bidid>/delete15/', views.delete15, name='delete15'),

    path('<int:bidid>/descript16/', views.descript16, name='descript16'),
    path('<int:bidid>/load_descript16/', views.load_descript16, name='load_descript16'),
    path('<int:bidid>/load_quanity16/', views.load_quanity16, name='load_quanity16'),
    path('<int:bidid>/quant16/', views.quant16, name='quant16'),
    path('<int:bidid>/delete16/', views.delete16, name='delete16'),

    path('<int:bidid>/descript17/', views.descript17, name='descript17'),
    path('<int:bidid>/load_descript17/', views.load_descript17, name='load_descript17'),
    path('<int:bidid>/load_quanity17/', views.load_quanity17, name='load_quanity17'),
    path('<int:bidid>/quant17/', views.quant17, name='quant17'),
    path('<int:bidid>/delete17/', views.delete17, name='delete17'),

    path('<int:bidid>/descript18/', views.descript18, name='descript18'),
    path('<int:bidid>/load_descript18/', views.load_descript18, name='load_descript18'),
    path('<int:bidid>/load_quanity18/', views.load_quanity18, name='load_quanity18'),
    path('<int:bidid>/quant18/', views.quant18, name='quant18'),
    path('<int:bidid>/delete18/', views.delete18, name='delete18'),

    path('<int:bidid>/descript19/', views.descript19, name='descript19'),
    path('<int:bidid>/load_descript19/', views.load_descript19, name='load_descript19'),
    path('<int:bidid>/load_quanity19/', views.load_quanity19, name='load_quanity19'),
    path('<int:bidid>/quant19/', views.quant19, name='quant19'),
    path('<int:bidid>/delete19/', views.delete19, name='delete19'),

    path('<int:bidid>/descript20/', views.descript20, name='descript20'),
    path('<int:bidid>/load_descript20/', views.load_descript20, name='load_descript20'),
    path('<int:bidid>/load_quanity20/', views.load_quanity20, name='load_quanity20'),
    path('<int:bidid>/quant20/', views.quant20, name='quant20'),
    path('<int:bidid>/delete20/', views.delete20, name='delete20'),

    path('<int:bidid>/descript21/', views.descript21, name='descript21'),
    path('<int:bidid>/load_descript21/', views.load_descript21, name='load_descript21'),
    path('<int:bidid>/load_quanity21/', views.load_quanity21, name='load_quanity21'),
    path('<int:bidid>/quant21/', views.quant21, name='quant21'),
    path('<int:bidid>/delete21/', views.delete21, name='delete21'),

    path('<int:bidid>/materialtype/', views.materialtype, name='materialtype'),

    path('<int:bidid>/techlevel/', views.techlevel, name='techlevel'),
    path('<int:bidid>/techlevelhrs/', views.techlevelhrs, name='techlevelhrs'),
    path('<int:bidid>/load_techlevelhrs/', views.load_techlevelhrs, name='load_techlevelhrs'),

    path('<int:bidid>/techlevel2/', views.techlevel2, name='techlevel2'),
    path('<int:bidid>/techlevelhrs2/', views.techlevelhrs2, name='techlevelhrs2'),
    path('<int:bidid>/load_techlevel2hrs/', views.load_techlevel2hrs, name='load_techlevel2hrs'),

    path('<int:bidid>/techlevel3/', views.techlevel3, name='techlevel3'),
    path('<int:bidid>/techlevelhrs3/', views.techlevelhrs3, name='techlevelhrs3'),
    path('<int:bidid>/load_techlevel3hrs/', views.load_techlevel3hrs, name='load_techlevel3hrs'),

    path('<int:bidid>/techlevel4/', views.techlevel4, name='techlevel4'),
    path('<int:bidid>/techlevelhrs4/', views.techlevelhrs4, name='techlevelhrs4'),
    path('<int:bidid>/load_techlevel4hrs/', views.load_techlevel4hrs, name='load_techlevel4hrs'),

    path('mainsettingpage/', views.mainsettingpage, name='mainsettingpage'),

    path('packagepage1/', views.packagepage1, name='packagepage1'),
    path('package1/', views.package1, name='package1'),
    path('package1a/', views.package1a, name='package1a'),
    path('package1b/', views.package1b, name='package1b'),
    path('package1add/', views.package1add, name='package1add'),
    path('<int:id>/deletepackage1/', views.deletepackage1, name='deletepackage1'),
    path('<int:id>/deletepackage1a/', views.deletepackage1a, name='deletepackage1a'),

    path('packagepage2/', views.packagepage2, name='packagepage2'),
    path('package2/', views.package2, name='package2'),
    path('package2a/', views.package2a, name='package2a'),
    path('package2b/', views.package2b, name='package2b'),
    path('package2add/', views.package2add, name='package2add'),
    path('<int:id>/deletepackage2/', views.deletepackage2, name='deletepackage2'),
    path('<int:id>/deletepackage2a/', views.deletepackage2a, name='deletepackage2a'),

    path('packagepage3/', views.packagepage3, name='packagepage3'),
    path('package3/', views.package3, name='package3'),
    path('package3a/', views.package3a, name='package3a'),
    path('package3b/', views.package3b, name='package3b'),
    path('package3add/', views.package3add, name='package3add'),
    path('<int:id>/deletepackage3/', views.deletepackage3, name='deletepackage3'),
    path('<int:id>/deletepackage3a/', views.deletepackage3a, name='deletepackage3a'),

    path('packagepage4/', views.packagepage4, name='packagepage4'),
    path('package4/', views.package4, name='package4'),
    path('package4a/', views.package4a, name='package4a'),
    path('package4b/', views.package4b, name='package4b'),
    path('package4add/', views.package4add, name='package4add'),
    path('<int:id>/deletepackage4/', views.deletepackage4, name='deletepackage4'),
    path('<int:id>/deletepackage4a/', views.deletepackage4a, name='deletepackage4a'),


    path('package5/', views.package5, name='package5'),
    path('package5a/', views.package5a, name='package5a'),
    path('package5b/', views.package5b, name='package5b'),
    path('package5add/', views.package5add, name='package5add'),
    path('<int:id>/deletepackage5/', views.deletepackage5, name='deletepackage5'),
    path('<int:id>/deletepackage5a/', views.deletepackage5a, name='deletepackage5a'),


    path('package6/', views.package6, name='package6'),
    path('package6a/', views.package6a, name='package6a'),
    path('package6b/', views.package6b, name='package6b'),
    path('package6add/', views.package6add, name='package6add'),
    path('<int:id>/deletepackage6/', views.deletepackage6, name='deletepackage6'),
    path('<int:id>/deletepackage6a/', views.deletepackage6a, name='deletepackage6a'),


    path('package7/', views.package7, name='package7'),
    path('package7a/', views.package7a, name='package7a'),
    path('package7b/', views.package7b, name='package7b'),
    path('package7add/', views.package7add, name='package7add'),
    path('<int:id>/deletepackage7/', views.deletepackage7, name='deletepackage7'),
    path('<int:id>/deletepackage7a/', views.deletepackage7a, name='deletepackage7a'),

    path('package8/', views.package8, name='package8'),
    path('package8a/', views.package8a, name='package8a'),
    path('package8b/', views.package8b, name='package8b'),
    path('package8add/', views.package8add, name='package8add'),
    path('<int:id>/deletepackage8/', views.deletepackage8, name='deletepackage8'),
    path('<int:id>/deletepackage8a/', views.deletepackage8a, name='deletepackage8a'),

    path('package9/', views.package9, name='package9'),
    path('package9a/', views.package9a, name='package9a'),
    path('package9b/', views.package9b, name='package9b'),
    path('package9add/', views.package9add, name='package9add'),
    path('<int:id>/deletepackage9/', views.deletepackage9, name='deletepackage9'),
    path('<int:id>/deletepackage9a/', views.deletepackage9a, name='deletepackage9a'),

    path('package10/', views.package10, name='package10'),
    path('package10a/', views.package10a, name='package10a'),
    path('package10b/', views.package10b, name='package10b'),
    path('package10add/', views.package10add, name='package10add'),
    path('<int:id>/deletepackage10/', views.deletepackage10, name='deletepackage10'),
    path('<int:id>/deletepackage10a/', views.deletepackage10a, name='deletepackage10a'),

    path('package11/', views.package11, name='package11'),
    path('package11a/', views.package11a, name='package11a'),
    path('package11b/', views.package11b, name='package11b'),
    path('package11add/', views.package11add, name='package11add'),
    path('<int:id>/deletepackage11/', views.deletepackage11, name='deletepackage11'),
    path('<int:id>/deletepackage11a/', views.deletepackage11a, name='deletepackage11a'),

    path('package12/', views.package12, name='package12'),
    path('package12a/', views.package12a, name='package12a'),
    path('package12b/', views.package12b, name='package12b'),
    path('package12add/', views.package12add, name='package12add'),
    path('<int:id>/deletepackage12/', views.deletepackage12, name='deletepackage12'),
    path('<int:id>/deletepackage12a/', views.deletepackage12a, name='deletepackage12a'),

    path('package13/', views.package13, name='package13'),
    path('package13a/', views.package13a, name='package13a'),
    path('package13b/', views.package13b, name='package13b'),
    path('package13add/', views.package13add, name='package13add'),
    path('<int:id>/deletepackage13/', views.deletepackage13, name='deletepackage13'),
    path('<int:id>/deletepackage13a/', views.deletepackage13a, name='deletepackage13a'),

    path('package14/', views.package14, name='package14'),
    path('package14a/', views.package14a, name='package14a'),
    path('package14b/', views.package14b, name='package14b'),
    path('package14add/', views.package14add, name='package14add'),
    path('<int:id>/deletepackage14/', views.deletepackage14, name='deletepackage14'),
    path('<int:id>/deletepackage14a/', views.deletepackage14a, name='deletepackage14a'),

    path('package15/', views.package15, name='package15'),
    path('package15a/', views.package15a, name='package15a'),
    path('package15b/', views.package15b, name='package15b'),
    path('package15add/', views.package15add, name='package15add'),
    path('<int:id>/deletepackage15/', views.deletepackage15, name='deletepackage15'),
    path('<int:id>/deletepackage15a/', views.deletepackage15a, name='deletepackage15a'),

    path('package16/', views.package16, name='package16'),
    path('package16a/', views.package16a, name='package16a'),
    path('package16b/', views.package16b, name='package16b'),
    path('package16add/', views.package16add, name='package16add'),
    path('<int:id>/deletepackage16/', views.deletepackage16, name='deletepackage16'),
    path('<int:id>/deletepackage16a/', views.deletepackage16a, name='deletepackage16a'),

    path('packagenamechange/', views.packagenamechange, name='packagenamechange'),
    path('reviewpackages/', views.reviewpackages, name='reviewpackages'),

    path('<int:id>/changename1/', views.changename1, name='changename1'),
    path('<int:id>/acceptchangename1/', views.acceptchangename1, name='acceptchangename1'),
    path('<int:id>/changename2/', views.changename2, name='changename2'),
    path('<int:id>/acceptchangename2/', views.acceptchangename2, name='acceptchangename2'),
    path('<int:id>/changename3/', views.changename3, name='changename3'),
    path('<int:id>/acceptchangename3/', views.acceptchangename3, name='acceptchangename3'),
    path('<int:id>/changename4/', views.changename4, name='changename4'),
    path('<int:id>/acceptchangename4/', views.acceptchangename4, name='acceptchangename4'),
    path('<int:id>/changename5/', views.changename5, name='changename5'),
    path('<int:id>/acceptchangename5/', views.acceptchangename5, name='acceptchangename5'),
    path('<int:id>/changename6/', views.changename6, name='changename6'),
    path('<int:id>/acceptchangename6/', views.acceptchangename6, name='acceptchangename6'),
    path('<int:id>/changename7/', views.changename7, name='changename7'),
    path('<int:id>/acceptchangename7/', views.acceptchangename7, name='acceptchangename7'),
    path('<int:id>/changename8/', views.changename8, name='changename8'),
    path('<int:id>/acceptchangename8/', views.acceptchangename8, name='acceptchangename8'),
    path('<int:id>/changename9/', views.changename9, name='changename9'),
    path('<int:id>/acceptchangename9/', views.acceptchangename9, name='acceptchangename9'),
    path('<int:id>/changename10/', views.changename10, name='changename10'),
    path('<int:id>/acceptchangename10/', views.acceptchangename10, name='acceptchangename10'),
    path('<int:id>/changename11/', views.changename11, name='changename11'),
    path('<int:id>/acceptchangename11/', views.acceptchangename11, name='acceptchangename11'),
    path('<int:id>/changename12/', views.changename12, name='changename12'),
    path('<int:id>/acceptchangename12/', views.acceptchangename12, name='acceptchangename12'),
    path('<int:id>/changename13/', views.changename13, name='changename13'),
    path('<int:id>/acceptchangename13/', views.acceptchangename13, name='acceptchangename13'),
    path('<int:id>/changename14/', views.changename14, name='changename14'),
    path('<int:id>/acceptchangename14/', views.acceptchangename14, name='acceptchangename14'),
    path('<int:id>/changename15/', views.changename15, name='changename15'),
    path('<int:id>/acceptchangename15/', views.acceptchangename15, name='acceptchangename15'),
    path('<int:id>/changename16/', views.changename16, name='changename16'),
    path('<int:id>/acceptchangename16/', views.acceptchangename16, name='acceptchangename16'),

    path('<int:jobid>/print/', views.print, name='print'),
    path('<int:bidid>/contract/', views.contract, name='contract'),
    path('<int:bidid>/contractB/', views.contractB, name='contractB'),
    path('<int:bidid>/contractC/', views.contractC, name='contractC'),
    path('<int:bidid>/contractD/', views.contractD, name='contractD'),
    path('<int:bidid>/contractE/', views.contractE, name='contractE'),
    path('<int:jobid>/contractmulti2/', views.contractmulti2, name='contractmulti2'),
    path('<int:jobid>/contractmulti3/', views.contractmulti3, name='contractmulti3'),
    path('<int:jobid>/contractmulti4/', views.contractmulti4, name='contractmulti4'),
    path('<int:jobid>/contractmulti5/', views.contractmulti5, name='contractmulti5'),
    path('<int:bidid>/contractdate/', views.contractdate, name='contractdate'),
    path('<int:bidid>/depositdate/', views.depositdate, name='depositdate'),
    path('<int:bidid>/finalpaymentdate/', views.finalpaymentdate, name='finalpaymentdate'),
    path('<int:bidid>/load_contractdate/', views.load_contractdate, name='load_contractdate'),
    path('<int:bidid>/depositterms/', views.depositterms, name='depositterms'),
    path('<int:bidid>/deposittermsa/', views.deposittermsa, name='deposittermsa'),
    path('<int:bidid>/load_deposittermsa/', views.load_deposittermsa, name='load_deposittermsa'),
    path('<int:bidid>/finalterms/', views.finalterms, name='finalterms'),
    path('<int:bidid>/finaltermsa/', views.finaltermsa, name='finaltermsa'),
    path('<int:bidid>/load_finaltermsa/', views.load_finaltermsa, name='load_finaltermsa'),
    path('<int:bidid>/downpaymentdate/', views.downpaymentdate, name='downpaymentdate'),
    path('<int:bidid>/load_downpaymentdate/', views.load_downpaymentdate, name='load_downpaymentdate'),
    path('<int:bidid>/finalpaymentdate/', views.finalpaymentdate, name='finalpaymentdate'),
    path('<int:bidid>/load_finalpaymentdate/', views.load_finalpaymentdate, name='load_finalpaymentdate'),
    path('<int:bidid>/deposit/', views.deposit, name='deposit'),
    path('<int:bidid>/load_deposit/', views.load_deposit, name='load_deposit'),
    path('<int:bidid>/load_finalpayment/', views.load_finalpayment, name='load_finalpayment'),

    path('<int:bidid>/load_memo1a/', views.load_memo1a, name='load_memo1a'),
    path('<int:bidid>/load_memo2a/', views.load_memo2a, name='load_memo2a'),
    path('<int:bidid>/load_memo3a/', views.load_memo3a, name='load_memo3a'),
    path('<int:bidid>/load_memo4a/', views.load_memo4a, name='load_memo4a'),
    path('<int:bidid>/load_memo5a/', views.load_memo5a, name='load_memo5a'),
    path('<int:bidid>/load_memo6a/', views.load_memo6a, name='load_memo6a'),
    path('<int:bidid>/load_memo7a/', views.load_memo7a, name='load_memo7a'),
    path('<int:bidid>/load_memo8a/', views.load_memo8a, name='load_memo8a'),
    path('<int:bidid>/load_memo9a/', views.load_memo9a, name='load_memo9a'),
    path('<int:bidid>/load_memo10a/', views.load_memo10a, name='load_memo10a'),
    path('<int:bidid>/load_memo11a/', views.load_memo11a, name='load_memo11a'),
    path('<int:bidid>/load_memo12a/', views.load_memo12a, name='load_memo12a'),
    path('<int:bidid>/load_memo13a/', views.load_memo13a, name='load_memo13a'),
    path('<int:bidid>/load_memo14a/', views.load_memo14a, name='load_memo14a'),
    path('<int:bidid>/load_memo15a/', views.load_memo15a, name='load_memo15a'),
    path('<int:bidid>/load_memo16a/', views.load_memo16a, name='load_memo16a'),
    path('<int:bidid>/load_memo17a/', views.load_memo17a, name='load_memo17a'),
    path('<int:bidid>/load_memo18a/', views.load_memo18a, name='load_memo18a'),
    
    path('<int:bidid>/memo1/', views.memo1, name='memo1'),
    path('<int:bidid>/memo1a/', views.memo1a, name='memo1a'),
    path('<int:bidid>/memo2/', views.memo2, name='memo2'),
    path('<int:bidid>/memo2a/', views.memo2a, name='memo2a'),
    path('<int:bidid>/memo3/', views.memo3, name='memo3'),
    path('<int:bidid>/memo3a/', views.memo3a, name='memo3a'),
    path('<int:bidid>/memo4/', views.memo4, name='memo4'),
    path('<int:bidid>/memo4a/', views.memo4a, name='memo4a'),
    path('<int:bidid>/memo5/', views.memo5, name='memo5'),
    path('<int:bidid>/memo5a/', views.memo5a, name='memo5a'),
    path('<int:bidid>/memo6/', views.memo6, name='memo6'),
    path('<int:bidid>/memo6a/', views.memo6a, name='memo6a'),
    path('<int:bidid>/memo7/', views.memo7, name='memo7'),
    path('<int:bidid>/memo7a/', views.memo7a, name='memo7a'),
    path('<int:bidid>/memo8/', views.memo8, name='memo8'),
    path('<int:bidid>/memo8a/', views.memo8a, name='memo8a'),
    path('<int:bidid>/memo9/', views.memo9, name='memo9'),
    path('<int:bidid>/memo9a/', views.memo9a, name='memo9a'),
    path('<int:bidid>/memo10/', views.memo10, name='memo10'),
    path('<int:bidid>/memo10a/', views.memo10a, name='memo10a'),
    path('<int:bidid>/memo11/', views.memo11, name='memo11'),
    path('<int:bidid>/memo11a/', views.memo11a, name='memo11a'),
    path('<int:bidid>/memo12/', views.memo12, name='memo12'),
    path('<int:bidid>/memo12a/', views.memo12a, name='memo12a'),
    path('<int:bidid>/memo13/', views.memo13, name='memo13'),
    path('<int:bidid>/memo13a/', views.memo13a, name='memo13a'),
    path('<int:bidid>/memo14/', views.memo14, name='memo14'),
    path('<int:bidid>/memo14a/', views.memo14a, name='memo14a'),
    path('<int:bidid>/memo15/', views.memo15, name='memo15'),
    path('<int:bidid>/memo15a/', views.memo15a, name='memo15a'),
    path('<int:bidid>/memo16/', views.memo16, name='memo16'),
    path('<int:bidid>/memo16a/', views.memo16a, name='memo16a'),
    path('<int:bidid>/memo17/', views.memo17, name='memo17'),
    path('<int:bidid>/memo17a/', views.memo17a, name='memo17a'),
    path('<int:bidid>/memo18/', views.memo18, name='memo18'),
    path('<int:bidid>/memo18a/', views.memo18a, name='memo18a'),
    path('<int:bidid>/memo31/', views.memo31, name='memo31'),

    path('<int:bidid>/memo1_2/', views.memo1_2, name='memo1_2'),
    path('<int:bidid>/memo1a_2/', views.memo1a_2, name='memo1a_2'),
    path('<int:bidid>/memo2_2/', views.memo2_2, name='memo2_2'),
    path('<int:bidid>/memo2a_2/', views.memo2a_2, name='memo2a_2'),
    path('<int:bidid>/memo3_2/', views.memo3_2, name='memo3_2'),
    path('<int:bidid>/memo3a_2/', views.memo3a_2, name='memo3a_2'),
    path('<int:bidid>/memo4_2/', views.memo4_2, name='memo4_2'),
    path('<int:bidid>/memo4a_2/', views.memo4a_2, name='memo4a_2'),
    path('<int:bidid>/memo5_2/', views.memo5_2, name='memo5_2'),
    path('<int:bidid>/memo5a_2/', views.memo5a_2, name='memo5a_2'),
    path('<int:bidid>/memo6_2/', views.memo6_2, name='memo6_2'),
    path('<int:bidid>/memo6a_2/', views.memo6a_2, name='memo6a_2'),
    path('<int:bidid>/memo7_2/', views.memo7_2, name='memo7_2'),
    path('<int:bidid>/memo7a_2/', views.memo7a_2, name='memo7a_2'),
    path('<int:bidid>/memo8_2/', views.memo8_2, name='memo8_2'),
    path('<int:bidid>/memo8a_2/', views.memo8a_2, name='memo8a_2'),
    path('<int:bidid>/memo9_2/', views.memo9_2, name='memo9_2'),
    path('<int:bidid>/memo9a_2/', views.memo9a_2, name='memo9a_2'),
    path('<int:bidid>/memo10_2/', views.memo10_2, name='memo10_2'),
    path('<int:bidid>/memo10a_2/', views.memo10a_2, name='memo10a_2'),
    path('<int:bidid>/memo11_2/', views.memo11_2, name='memo11_2'),
    path('<int:bidid>/memo11a_2/', views.memo11a_2, name='memo11a_2'),
    path('<int:bidid>/memo12_2/', views.memo12_2, name='memo12_2'),
    path('<int:bidid>/memo12a_2/', views.memo12a_2, name='memo12a_2'),
    path('<int:bidid>/memo13_2/', views.memo13_2, name='memo13_2'),
    path('<int:bidid>/memo13a_2/', views.memo13a_2, name='memo13a_2'),
    path('<int:bidid>/memo14_2/', views.memo14_2, name='memo14_2'),
    path('<int:bidid>/memo14a_2/', views.memo14a_2, name='memo14a_2'),
    path('<int:bidid>/memo15_2/', views.memo15_2, name='memo15_2'),
    path('<int:bidid>/memo15a_2/', views.memo15a_2, name='memo15a_2'),
    path('<int:bidid>/memo16_2/', views.memo16_2, name='memo16_2'),
    path('<int:bidid>/memo16a_2/', views.memo16a_2, name='memo16a_2'),
    path('<int:bidid>/memo17_2/', views.memo17_2, name='memo17_2'),
    path('<int:bidid>/memo17a/', views.memo17a_2, name='memo17a_2'),
    path('<int:bidid>/memo18_2/', views.memo18_2, name='memo18_2'),
    path('<int:bidid>/memo18a_2/', views.memo18a_2, name='memo18a_2'),
    path('<int:bidid>/memo31_2/', views.memo31_2, name='memo31_2'),

    path('<int:bidid>/memo1_3/', views.memo1_3, name='memo1_3'),
    path('<int:bidid>/memo1a_3/', views.memo1a_3, name='memo1a_3'),
    path('<int:bidid>/memo2_3/', views.memo2_3, name='memo2_3'),
    path('<int:bidid>/memo2a_3/', views.memo2a_3, name='memo2a_3'),
    path('<int:bidid>/memo3_3/', views.memo3_3, name='memo3_3'),
    path('<int:bidid>/memo3a_3/', views.memo3a_3, name='memo3a_3'),
    path('<int:bidid>/memo4_3/', views.memo4_3, name='memo4_3'),
    path('<int:bidid>/memo4a_3/', views.memo4a_3, name='memo4a_3'),
    path('<int:bidid>/memo5_3/', views.memo5_3, name='memo5_3'),
    path('<int:bidid>/memo5a_3/', views.memo5a_3, name='memo5a_3'),
    path('<int:bidid>/memo6_3/', views.memo6_3, name='memo6_3'),
    path('<int:bidid>/memo6a_3/', views.memo6a_3, name='memo6a_3'),
    path('<int:bidid>/memo7_3/', views.memo7_3, name='memo7_3'),
    path('<int:bidid>/memo7a_3/', views.memo7a_3, name='memo7a_3'),
    path('<int:bidid>/memo8_3/', views.memo8_3, name='memo8_3'),
    path('<int:bidid>/memo8a_3/', views.memo8a_3, name='memo8a_3'),
    path('<int:bidid>/memo9_3/', views.memo9_3, name='memo9_3'),
    path('<int:bidid>/memo9a_3/', views.memo9a_3, name='memo9a_3'),
    path('<int:bidid>/memo10_3/', views.memo10_3, name='memo10_3'),
    path('<int:bidid>/memo10a_3/', views.memo10a_3, name='memo10a_3'),
    path('<int:bidid>/memo11_3/', views.memo11_3, name='memo11_3'),
    path('<int:bidid>/memo11a_3/', views.memo11a_3, name='memo11a_3'),
    path('<int:bidid>/memo12_3/', views.memo12_3, name='memo12_3'),
    path('<int:bidid>/memo12a_3/', views.memo12a_3, name='memo12a_3'),
    path('<int:bidid>/memo13_3/', views.memo13_3, name='memo13_3'),
    path('<int:bidid>/memo13a_3/', views.memo13a_3, name='memo13a_3'),
    path('<int:bidid>/memo14_3/', views.memo14_3, name='memo14_3'),
    path('<int:bidid>/memo14a_3/', views.memo14a_3, name='memo14a_3'),
    path('<int:bidid>/memo15_3/', views.memo15_3, name='memo15_3'),
    path('<int:bidid>/memo15a_3/', views.memo15a_3, name='memo15a_3'),
    path('<int:bidid>/memo16_3/', views.memo16_3, name='memo16_3'),
    path('<int:bidid>/memo16a_3/', views.memo16a_3, name='memo16a_3'),
    path('<int:bidid>/memo17_3/', views.memo17_3, name='memo17_3'),
    path('<int:bidid>/memo17a/', views.memo17a_3, name='memo17a_3'),
    path('<int:bidid>/memo18_3/', views.memo18_3, name='memo18_3'),
    path('<int:bidid>/memo18a_3/', views.memo18a_3, name='memo18a_3'),
    path('<int:bidid>/memo31_3/', views.memo31_3, name='memo31_3'),

    path('<int:bidid>/memo1_4/', views.memo1_4, name='memo1_4'),
    path('<int:bidid>/memo1a_4/', views.memo1a_4, name='memo1a_4'),
    path('<int:bidid>/memo2_4/', views.memo2_4, name='memo2_4'),
    path('<int:bidid>/memo2a_4/', views.memo2a_4, name='memo2a_4'),
    path('<int:bidid>/memo3_4/', views.memo3_4, name='memo3_4'),
    path('<int:bidid>/memo3a_4/', views.memo3a_4, name='memo3a_4'),
    path('<int:bidid>/memo4_4/', views.memo4_4, name='memo4_4'),
    path('<int:bidid>/memo4a_4/', views.memo4a_4, name='memo4a_4'),
    path('<int:bidid>/memo5_4/', views.memo5_4, name='memo5_4'),
    path('<int:bidid>/memo5a_4/', views.memo5a_4, name='memo5a_4'),
    path('<int:bidid>/memo6_4/', views.memo6_4, name='memo6_4'),
    path('<int:bidid>/memo6a_4/', views.memo6a_4, name='memo6a_4'),
    path('<int:bidid>/memo7_4/', views.memo7_4, name='memo7_4'),
    path('<int:bidid>/memo7a_4/', views.memo7a_4, name='memo7a_4'),
    path('<int:bidid>/memo8_4/', views.memo8_4, name='memo8_4'),
    path('<int:bidid>/memo8a_4/', views.memo8a_4, name='memo8a_4'),
    path('<int:bidid>/memo9_4/', views.memo9_4, name='memo9_4'),
    path('<int:bidid>/memo9a_4/', views.memo9a_4, name='memo9a_4'),
    path('<int:bidid>/memo10_4/', views.memo10_4, name='memo10_4'),
    path('<int:bidid>/memo10a_4/', views.memo10a_4, name='memo10a_4'),
    path('<int:bidid>/memo11_4/', views.memo11_4, name='memo11_4'),
    path('<int:bidid>/memo11a_4/', views.memo11a_4, name='memo11a_4'),
    path('<int:bidid>/memo12_4/', views.memo12_4, name='memo12_4'),
    path('<int:bidid>/memo12a_4/', views.memo12a_4, name='memo12a_4'),
    path('<int:bidid>/memo13_4/', views.memo13_4, name='memo13_4'),
    path('<int:bidid>/memo13a_4/', views.memo13a_4, name='memo13a_4'),
    path('<int:bidid>/memo14_4/', views.memo14_4, name='memo14_4'),
    path('<int:bidid>/memo14a_4/', views.memo14a_4, name='memo14a_4'),
    path('<int:bidid>/memo15_4/', views.memo15_4, name='memo15_4'),
    path('<int:bidid>/memo15a_4/', views.memo15a_4, name='memo15a_4'),
    path('<int:bidid>/memo16_4/', views.memo16_4, name='memo16_4'),
    path('<int:bidid>/memo16a_4/', views.memo16a_4, name='memo16a_4'),
    path('<int:bidid>/memo17_4/', views.memo17_4, name='memo17_4'),
    path('<int:bidid>/memo17a/', views.memo17a_4, name='memo17a_4'),
    path('<int:bidid>/memo18_4/', views.memo18_4, name='memo18_4'),
    path('<int:bidid>/memo18a_4/', views.memo18a_4, name='memo18a_4'),
    path('<int:bidid>/memo31_4/', views.memo31_4, name='memo31_4'),

    path('<int:bidid>/memo1_5/', views.memo1_5, name='memo1_5'),
    path('<int:bidid>/memo1a_5/', views.memo1a_5, name='memo1a_5'),
    path('<int:bidid>/memo2_5/', views.memo2_5, name='memo2_5'),
    path('<int:bidid>/memo2a_5/', views.memo2a_5, name='memo2a_5'),
    path('<int:bidid>/memo3_5/', views.memo3_5, name='memo3_5'),
    path('<int:bidid>/memo3a_5/', views.memo3a_5, name='memo3a_5'),
    path('<int:bidid>/memo4_5/', views.memo4_5, name='memo4_5'),
    path('<int:bidid>/memo4a_5/', views.memo4a_5, name='memo4a_5'),
    path('<int:bidid>/memo5_5/', views.memo5_5, name='memo5_5'),
    path('<int:bidid>/memo5a_5/', views.memo5a_5, name='memo5a_5'),
    path('<int:bidid>/memo6_5/', views.memo6_5, name='memo6_5'),
    path('<int:bidid>/memo6a_5/', views.memo6a_5, name='memo6a_5'),
    path('<int:bidid>/memo7_5/', views.memo7_5, name='memo7_5'),
    path('<int:bidid>/memo7a_5/', views.memo7a_5, name='memo7a_5'),
    path('<int:bidid>/memo8_5/', views.memo8_5, name='memo8_5'),
    path('<int:bidid>/memo8a_5/', views.memo8a_5, name='memo8a_5'),
    path('<int:bidid>/memo9_5/', views.memo9_5, name='memo9_5'),
    path('<int:bidid>/memo9a_5/', views.memo9a_5, name='memo9a_5'),
    path('<int:bidid>/memo10_5/', views.memo10_5, name='memo10_5'),
    path('<int:bidid>/memo10a_5/', views.memo10a_5, name='memo10a_5'),
    path('<int:bidid>/memo11_5/', views.memo11_5, name='memo11_5'),
    path('<int:bidid>/memo11a_5/', views.memo11a_5, name='memo11a_5'),
    path('<int:bidid>/memo12_5/', views.memo12_5, name='memo12_5'),
    path('<int:bidid>/memo12a_5/', views.memo12a_5, name='memo12a_5'),
    path('<int:bidid>/memo13_5/', views.memo13_5, name='memo13_5'),
    path('<int:bidid>/memo13a_5/', views.memo13a_5, name='memo13a_5'),
    path('<int:bidid>/memo14_5/', views.memo14_5, name='memo14_5'),
    path('<int:bidid>/memo14a_5/', views.memo14a_5, name='memo14a_5'),
    path('<int:bidid>/memo15_5/', views.memo15_5, name='memo15_5'),
    path('<int:bidid>/memo15a_5/', views.memo15a_5, name='memo15a_5'),
    path('<int:bidid>/memo16_5/', views.memo16_5, name='memo16_5'),
    path('<int:bidid>/memo16a_5/', views.memo16a_5, name='memo16a_5'),
    path('<int:bidid>/memo17_5/', views.memo17_5, name='memo17_5'),
    path('<int:bidid>/memo17a/', views.memo17a_5, name='memo17a_5'),
    path('<int:bidid>/memo18_5/', views.memo18_5, name='memo18_5'),
    path('<int:bidid>/memo18a_5/', views.memo18a_5, name='memo18a_5'),
    path('<int:bidid>/memo31_5/', views.memo31_5, name='memo31_5'),

    path('custpageloc', views.custpageloc, name='custpageloc'),
    path('multiformb', views.multiformb, name='multiformb'),

    path('<int:bidid>/targetnetprofit/', views.targetnetprofit, name='targetnetprofit'),
    path('<int:bidid>/netprofit/', views.netprofit, name='netprofit'),
    path('<int:bidid>/load_netprofit/', views.load_netprofit, name='load_netprofit'),
    path('<int:bidid>/load_costplusprofit/', views.load_costplusprofit, name='load_costplusprofit'),
    path('<int:bidid>/load_totalsubcost/', views.load_totalsubcost, name='load_totalsubcost'),
    path('<int:bidid>/load_finaljobcost/', views.load_finaljobcost, name='load_finaljobcost'),
    path('<int:bidid>/load_profit/', views.load_profit, name='load_profit'),
    path('<int:bidid>/changetargetnet/', views.changetargetnet, name='changetargetnet'),

    path('duplicate2/', views.duplicate2, name='duplicate2'),
    path('duplicate22/', views.duplicate22, name='duplicate22'),
    path('duplicateequip/', views.duplicateequip, name='duplicateequip'),
    path('modeldup/', views.modeldup, name='modeldup'),
    path('descriptiondup/', views.descriptiondup, name='descriptiondup'),
    path('btudup/', views.btudup, name='btudup'),
    path('costdup/', views.costdup, name='costdup'),
    path('heightdup/', views.heightdup, name='heightdup'),
    path('widthdup/', views.widthdup, name='widthdup'),
    path('depthdup/', views.depthdup, name='depthdup'),

    path('plenumheight/', views.plenumheight, name='plenumheight'),
    path('load_plenumheight', views.load_plenumheight, name='load_plenumheight'),
    path('plenumwidth/', views.plenumwidth, name='plenumwidth'),
    path('load_plenumwidth', views.load_plenumwidth, name='load_plenumwidth'),
    path('plenumdepth/', views.plenumdepth, name='plenumdepth'),
    path('load_plenumdepth', views.load_plenumdepth, name='load_plenumdepth'),

    path('load_plenumwidthAB', views.load_plenumwidthAB, name='load_plenumwidthAB'),
    path('load_existfurnconfigAB', views.load_existfurnconfigAB, name='load_existfurnconfigAB'),
    path('load_existfurnwidthAB', views.load_existfurnwidthAB, name='load_existfurnwidthAB'),


    path('<int:bidid>/materialtype3', views.materialtype3, name='materialtype3'),
    path('<int:bidid>/update8b', views.update8b, name='update8b'),
    path('<int:bidid>/update9b', views.update9b, name='update9b'),
    path('<int:bidid>/update10b', views.update10b, name='update10b'),
    path('<int:bidid>/update11b', views.update11b, name='update11b'),
    path('<int:bidid>/update12b', views.update12b, name='update12b'),
    path('<int:bidid>/update13b', views.update13b, name='update13b'),
    path('<int:bidid>/update14b', views.update14b, name='update14b'),
    path('<int:bidid>/update15b', views.update15b, name='update15b'),
    path('<int:bidid>/update16b', views.update16b, name='update16b'),
    path('<int:bidid>/update17b', views.update17b, name='update17b'),
    path('<int:bidid>/update18b', views.update18b, name='update18b'),
    path('<int:bidid>/update19b', views.update19b, name='update19b'),
    path('<int:bidid>/update20b', views.update20b, name='update20b'),
    path('<int:bidid>/update21b', views.update21b, name='update21b'),
    
    path('<int:bidid>/load_descript9b/', views.load_descript9b, name='load_descript9b'),
    path('<int:bidid>/load_descript10b/', views.load_descript10b, name='load_descript10b'),
    path('<int:bidid>/load_descript11b/', views.load_descript11b, name='load_descript11b'),
    path('<int:bidid>/load_descript12b/', views.load_descript12b, name='load_descript12b'),
    path('<int:bidid>/load_descript13b/', views.load_descript13b, name='load_descript13b'),
    path('<int:bidid>/load_descript14b/', views.load_descript14b, name='load_descript14b'),
    path('<int:bidid>/load_descript15b/', views.load_descript15b, name='load_descript15b'),
    path('<int:bidid>/load_descript16b/', views.load_descript16b, name='load_descript16b'),
    path('<int:bidid>/load_descript17b/', views.load_descript17b, name='load_descript17b'),
    path('<int:bidid>/load_descript18b/', views.load_descript18b, name='load_descript18b'),
    path('<int:bidid>/load_descript19b/', views.load_descript19b, name='load_descript19b'),
    path('<int:bidid>/load_descript20b/', views.load_descript20b, name='load_descript20b'),
    path('<int:bidid>/load_descript21b/', views.load_descript21b, name='load_descript21b'),

    path('laborrates', views.laborrates, name='laborrates'),
    path('addnewtechlevel/', views.addnewtechlevel, name='addnewtechlevel'),

    path('<int:id>/changetechrate/', views.changetechrate, name='changetechrate'),
    path('<int:id>/changelaborrate/', views.changelaborrate, name='changelaborrate'),
    path('<int:id>/deletetech/', views.deletetech, name='deletetech'),
    path('<int:id>/newtech2/', views.newtech2, name='newtech2'),
    path('levelnewtech/', views.levelnewtech, name='levelnewtech'),
    path('ratenewtech/', views.ratenewtech, name='ratenewtech'),
    path('deletenewtech/', views.deletenewtech, name='deletenewtech'),


    path('<int:bidid>/load_equiprow1/', views.load_equiprow1, name='load_equiprow1'),




]